### ISSUE TITLE
Docker build fails with the following error

### ISSUE THREAD

**Issue by openemail** [tiredofit/docker-db-backup#10]
+ apk add --virtual .db-backup-run-deps bzip2 mongodb-tools mariadb-client libressl pigz postgresql postgresql-client redis xz
ERROR: unsatisfiable constraints:
  mongodb-tools (missing):

**Comment by tiredofit** [comment]
Something is happening with Alpine packages right now and they've removed mongodb* from edge and even testing. I haven't seen anything on the development list but wondering if its related to their new [SSPL licensing](https://www.enterprisedb.com/blog/mongodb-still-open-source).

I'm letting it simmer for a few days before I do a deep dive in, building would be a pain in the neck.

**Comment by tiredofit** [comment]
I've fixed this issue by relying on building mongodb from aports throgh a [new repo](https://github.com/tiredofit/docker-mongo-builder) - so you should be able to build this on your own now!
