### ISSUE TITLE
add environment variable

### ISSUE THREAD

**Issue by stefanh12** [tiredofit/docker-db-backup#104]
**Description of the feature**

Backup to a S3 compatible host with https(default), like minio depends on a valid/trusted SSL certificate. There is no way currently to either add the certificate as a trusted or turn off ssl validation. The backup now fails:

`CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)`

the underlying aws cli command line can take a parameter,  --no-verify-ssl and the backups would work to self signed S3 hosts. Best would be to configure this with env variable that if set would add that line to the command

**Benftits of feature**

Most non cloud deployments will have a self signed certificate for S3 backup locations. Now, its not possible to backup to a S3 compatible host that does not have a valid trusted certificate. Thus the S3 feature is useless unless only using http and that is not compatible with most other clients.
**Additional context**

**Comment by tiredofit** [comment]
Seems reasonable enough to do. I support it. 

Tell me though - what would be a command line I would use to allow to use my own CA cert? I can build that in too and one can map a volume to the certs.

**Comment by stefanh12** [comment]
For removing cert validation the below change should work I think, 
`            aws ${PARAM_AWS_ENDPOINT_URL} s3 cp ${TEMP_LOCATION}/${target} s3://${S3_BUCKET}/${S3_PATH}/${target} --no-verify-ssl
`
That is without using a env to set the --no-verify-ssl

For the own CA validation, I'm out on a limb but from what I can [read ](https://www.shellhacks.com/aws-cli-ssl-validation-failed-solved/)there are 2 ways:

- use $ export AWS_CA_BUNDLE="/data/ca-certs/ca-bundle.pem" where /data/ca-certs would be mapped to a volume where to place the pem file
- ca_bundle setting in the config file and mapping a volume to the pem file

I think option one is quick but has a security issue, but most home users I think would be ok with that. Option 2 I think the only viable version is using the export variable and volume mapping, seems not that hard and is more secure

**Comment by tiredofit** [comment]
Has been added to `3.0.0` 

Both options, have a peek at the README on how it works.

**Comment by stefanh12** [comment]
Cool!

Tested without adding any of the new parameters, and it worked just fine without verifying the cert.
I set S3_CERT_SKIP_VERIFY to FALSE and it still worked, without pem file. 

I tried to test the certificate validation, I'm on unraid and I mapped /data/ca-certs first , then I set S3_CERT_CA_FILE to the path /data/ca-certs/ca-bundle.pem but its still not verifying the cert

There could be something different with running it on unraid with setting the variable S3_CERT_SKIP_VERIFY seems to be default value either way :)

**Comment by tiredofit** [comment]
Interesting. There is a tonne of output if you wanted to see the s3 command executing by setting `DEBUG_MODE=TRUE`. 

I am cheating a bit here, the cert and the S3_CERT_SKIP_VERIFY option all go into the same variable like so:

````bash
          if [ -f "${S3_CERT_CA_FILE}" ] ; then
                print_debug "Using Custom CA for S3 Backups"
                s3_ssl=" --ca-bundle ${S3_CERT_CA_FILE}"
            fi
            if var_true "${S3_CERT_SKIP_VERIFY}" ; then
                print_debug "Skipping SSL verification for HTTPS S3 Hosts"
                s3_ssl="${s3_ssl} --no-verify-ssl"
            fi
````

I will break it apart and see if that gives you any other results - I've noticed a few other anomalies which I'll push with `3.0.2` shortly.

**Comment by stefanh12** [comment]
yeah, Im not the best to understand the code too but ill see if I can get some debugs for you o 3.0.2 when you have it :)
