### ISSUE TITLE
Add S3 option to automatically delete old backups

### ISSUE THREAD

**Issue by gpetrov** [tiredofit/docker-db-backup#105]
**Description of the feature**
It will be very useful to specify how many backups you want to keep on the S3.
Then after a new successful backup and upload to s3, older backups can be removed

**Benefits of feature**
This will be very useful as automatic cleanup but not only time based but also based on the number of successful backups.

**Additional context**
Maybe something like this, but then based on the number of backups instead of time.
https://gitlab.com/-/snippets/1967872

**Comment by tiredofit** [comment]
This was added in `3.3.0` to follow the same as when backing up to filesystem still based on time.
