### ISSUE TITLE
Ambiguous Redirects with v3.0.14

### ISSUE THREAD

**Issue by mtompkins** [tiredofit/docker-db-backup#108]
### Summary

Since last tagged push of 3.0.14, backups fail with following error:

```
/assets/functions/10-db-backup: line 165: ${TEMP_LOCATION}/${target}: ambiguous redirect
mysqldump: Got errno 32 on write
2022-03-22.11:47:52 [ERROR] ** [db-backup] Backup reported errors
2022-03-22.11:47:52 [NOTICE] ** [db-backup] Generating MD5 for ...<redacted>...
```

### Steps to reproduce

1. Using docker based container with provided docker-compose sample.

### What is the expected *correct* behavior?

Backups succeed

**Comment by tiredofit** [comment]
Can you tell me what your earlier version was before? Perhaps you have the hash lying around? 3.0.14 was a fairly minor change, cosmetic I would say.

**Comment by mtompkins** [comment]
Unfortunately, it's hard to tell as I use watchtower to manage updates. Based on your tag history I would think it's between 3.0.4 and 3.0.6. (My updates hit at about 10:30AM CDT).

Thanks for your work on this as well.

**Comment by tiredofit** [comment]
`docker images | grep db-backup` should get you a image ID like so:

````bash
docker images | grep db-backup
tiredofit/db-backup                                           latest          508f1887a826   2 hours ago    532MB
tiredofit/db-backup                                           <none>          2666831a919b   18 hours ago   532MB
tiredofit/db-backup                                           <none>          124c5617f62e   20 hours ago   532MB
tiredofit/db-backup                                           <none>          18ffbc47438c   21 hours ago   532MB
tiredofit/db-backup                                           <none>          cfa195aa77c4   23 hours ago   532MB
tiredofit/db-backup                                           <none>          563971c4a702   25 hours ago   532MB
tiredofit/db-backup                                           <none>          2a187ee412b0   26 hours ago   532MB
tiredofit/db-backup                                           <none>          e8c4e98ef100   4 days ago     537MB
tiredofit/db-backup                                           <none>          b5c57d573acc   4 days ago     537MB
tiredofit/db-backup                                           <none>          b171db3182ed   5 days ago     536MB
tiredofit/db-backup                                           <none>          f41486977c46   5 weeks ago    535MB
````

Then you can inspect the image and get the version label I have embedded:

````bash
 docker image inspect 2a187ee412b0 | grep version
                "tiredofit.base.git_changelog_version": "7.5.2",
                "tiredofit.base.runtime_version": "3.15",
                "tiredofit.db-backup.git_changelog_version": "3.0.3"
````

**Comment by tiredofit** [comment]
Ahh yuck. There were alot of micro changes done yesterday. I'm going to have to squash all commits and run a diff that way. I will look into this after I sort out a few other things..

**Comment by mtompkins** [comment]
Been there. Sorry to be the bearer of annoyance.

**Comment by tiredofit** [comment]
Interesting. I'm not seeing where this has gone sideways in all the commits. 
Do you think its worth while you can add a `DEBUG_MODE=TRUE` to your environment variables, then enter into the container and execute

`echo "echo DEBUG TEMP LOCATION: \${TEMP_LOCATION}" >> /assets/defaults/10-db-backup`

Following that, execute `backup-now`

I'm curious to see what that `mysqldump` statement looks like (please, clean off any personal info ala db name, db user, db host, db pass.

I'd love to know what "DEBUG_TEMP_LOCATION" spits out as the problem seems to lie there.

**Comment by mtompkins** [comment]
I'll have to come back to it, but I did try quickly and it seems to be having difficulty connecting to the db.
I ran this without the DEBUG set to limit spam. The DB is up and running and accessible.

```
[tiredofit/db-backup:3.0.14 12:31:11] # backup-now
** Performing Manual Backup
/assets/defaults/10-db-backup: line 27: DEBUG: command not found
2022-03-22.12:31:18 [WARN] ** [db-backup] MySQL/MariaDB Server 'mariadb' is not accessible, retrying.. (5 seconds so far)
2022-03-22.12:31:23 [WARN] ** [db-backup] MySQL/MariaDB Server 'mariadb' is not accessible, retrying.. (10 seconds so far)
2022-03-22.12:31:28 [WARN] ** [db-backup] MySQL/MariaDB Server 'mariadb' is not accessible, retrying.. (15 seconds so far)
2022-03-22.12:31:33 [WARN] ** [db-backup] MySQL/MariaDB Server 'mariadb' is not accessible, retrying.. (20 seconds so far)
^C
[tiredofit/db-backup:3.0.14 12:31:34] # ping mariadb
PING mariadb (192.168.91.3) 56(84) bytes of data.
64 bytes from mariadb.data_layer (192.168.91.3): icmp_seq=1 ttl=64 time=0.055 ms
64 bytes from mariadb.data_layer (192.168.91.3): icmp_seq=2 ttl=64 time=0.030 ms
64 bytes from mariadb.data_layer (192.168.91.3): icmp_seq=3 ttl=64 time=0.039 ms
```

**Comment by tiredofit** [comment]
Ahh it looks as if that one liner I asked to put into /assets/defaults/10-db-backup didn't go in properly.
Let me whip up a develop image for you.

**Comment by mtompkins** [comment]
No it did - don't go to any trouble. I'll have more for you when I can.

**Comment by tiredofit** [comment]
No problem. Theres a `tiredofit/db-backup:develop` in place right now that will give those values when you run a `backup-now` on the command line and only output whats happening with the mysqldump command.

**Comment by mtompkins** [comment]
A bit more ... I break out of the script and try to connect which is successful.

```
+ print_warn 'MySQL/MariaDB Server '\''mariadb'\'' is not accessible, retrying.. (30 seconds so far)'
+ output_off
+ '[' true = true ']'
+ set +x
2022-03-22.13:43:17 [WARN] /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server 'mariadb' is not accessible, retrying.. (30 seconds so far)
+ mysqladmin -u -P3306 -hmariadb status
+ sleep 5
+ ((  COUNTER+=5  ))
+ print_warn 'MySQL/MariaDB Server '\''mariadb'\'' is not accessible, retrying.. (35 seconds so far)'
+ output_off
+ '[' true = true ']'
+ set +x
2022-03-22.13:43:22 [WARN] /etc/services.available/10-db-backup/run ** [db-backup] MySQL/MariaDB Server 'mariadb' is not accessible, retrying.. (35 seconds so far)
+ mysqladmin -u -P3306 -hmariadb status
+ sleep 5
^C
[tiredofit/db-backup:3.0.14 13:43:22] # mysqladmin -u root -p -P3306 -hmariadb status
Enter password: 
Uptime: 4635  Threads: 24  Questions: 12847  Slow queries: 0  Opens: 232  Open tables: 226  Queries per second avg: 2.771
```

**Comment by mtompkins** [comment]
Noticed the following:
```
++ dbpass='<redacted>'
++ dbtype=mariadb
++ dbuser=rootecho
```
Note `dbuser` above is incorrect.

**Comment by tiredofit** [comment]
Can you try this with `tiredofit/db-backup:develop`

**Comment by mtompkins** [comment]
...
```
DEBUG_TEMP_LOCATION: /tmp/backups
WORKING DIR: /
+ mysqldump --max-allowed-packet=512M -h mariadb -P 3306 -uroot --single-transaction --routines --databases <redacted> <redacted> <redacted> 
+ pixz -3 -p 12
/assets/functions/10-db-backup: line 168: ${TEMP_LOCATION}/${target}: ambiguous redirect
mysqldump: Got errno 32 on write
+ exit_code=1
+ set +x
```

**Comment by tiredofit** [comment]
Thanks, helpful that things are working the way that I anticipated. 
Since you are using `root` as a DB_USER are you also using `SPLIT_DB=TRUE` ?

**Comment by mtompkins** [comment]
```
environment:
      - DB_TYPE=mariadb
      - DB_HOST=mariadb
      #- DB_NAME=
      - DB_USER=root
      - DB_PASS=$MYSQL_ROOT_PASSWORD
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=+1
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=XZ
      - PARALLEL_COMPRESSION=FALSE
      - SPLIT_DB=TRUE
      - SIZE_VALUE=megabytes
   ```

**Comment by tiredofit** [comment]
OK! I probably should have asked for that at the very beginning :) Let me try to recreate on my end. I'll be able to circle to it in an hour or so. Giving performance reviews today :octopus: and in and out of ability to debug.

**Comment by mtompkins** [comment]
No worries and thanks for leaning in. FWIW I did disable XZ in hopes I could point at it as a cause. It fails regardless.

**Comment by tiredofit** [comment]
I did clean up a bit of my functions in terms of compresison and found something off with BZ but not with XZ. I have a sample MariaDB 10.6 server with 10 databases in it, where I am backing up via root I believe the same as you, and other than the blip with BZ all seems to be working. Are there any interesting characters in your databases? Trying to think of something not so obvious here...

**Comment by mtompkins** [comment]
In your `/assets/functions/10-db-backup`
in function `backup_mysql()`
your iteration over "${DATABASES} is not parsing correctly.

For example if my databases are **foo**, **bar**, and **bat** and I echo ${db} as in:
```
for db in "${DATABASES}" ; do
                echo "DEBUG-ADD: Working on Database: ${db}"
```
I get an output of:
```
DEBUG-ADD: Working on Database: foo                                                                                                         
bar
bat
```
So the **${DATABASES}** variable is not correctly iterated over.
If would therefore seem how you are constructing the array is problematic.
`DATABASES=$(mysql -h ${dbhost} -P $dbport -u$dbuser --batch -e "SHOW DATABASES;" | grep -v Database | grep -v schema)`

I tried to simply iterate over that variable and it does not parse correctly.

HTH

**Comment by tiredofit** [comment]
Found it! It was introduced in the `3.0.0` rebuild.  As per usual, it was the least obvious to my eye - It was a double quote which forces the for loop to only iterate once and clobbers the array. `3.0.16` or `latest` should give you the fix.

While I was looking at that section last night it brought back memories of near 5 years ago wanting to do something more with it. In future, I'd like to do the following:

- Change the way `SPLIT_DB` functions by grabbing what db's are available move it into `DB_NAME` in the form of 'db1,db2,db3'. 
- For situations where one would want to just use the old function of automatically determining what databases are available it could take a parameter of `ALL`
- By default `SPLIT_DB` would be `TRUE`, eg one file per database, which would then fire the "extras" (log, post logs, monitoring triggers) per backed up database.
- When `SPLIT_DB=FALSE` it would just take all backups into one big blob.
- We could also introduce `DB_NAME_EXCLUDE`, a comma separated list of db's NOT to backup when `ALL` is in place.

I don't know how many people are actually using `SPLIT_DB` or backing up as `root` so, since I've got you here, I mine as well solicit some feedback :)

**Comment by mtompkins** [comment]
Can confirm changes have successfully fixed the bug. Thanks!
Feedback:
I shouldn't use `root`. I can't remember why I moved to using it, there had been a reason because I have a user `backup` with necessary permissions...I vaguely remember it being somehow docker related. For the use-case there isn't increased risk for me so I just don't think about it.

By your list:

- Change the way `SPLIT_DB` functions by grabbing what db's are available move it into DB_NAME in the form of db1,db2,db3.
> I would think this approach reduces your chance of having array surprises.
- For situations where one would want to just use the old function of automatically determining what databases are available it could take a parameter of ALL
> I like this. Better to have all variables assigned versus defaults or empty IMO. You can then sanity check.
- By default `SPLIT_DB` would be TRUE, eg one file per database, which would then fire the "extras" (log, post logs, monitoring triggers) per backed up database.
> I like this as well. My approach is, I want to be able to easily get at a specific db instance backup.
- When SPLIT_DB=FALSE it would just take all backups into one big blob.
> Sure
- We could also introduce DB_NAME_EXCLUDE, a comma separated list of db's NOT to backup when ALL is in place.
> A reasonable edition but redundant as they can exclude based on the DB_NAME variable. You'd wind up having to sanity check for existence in one variable and not the other? If it were me, I don't think I'd add it.

Thanks again for your work on this container. I use XtraBackup elsewhere but prefer the simplicity here.

**Comment by tiredofit** [comment]
Glad we're back on track - and thanks for sticking it through the past day while I juggled other things. I'll close off the issue.

**Comment by tiredofit** [comment]
`3.1.0` contains all of the above. Commit is here - There may be a bit of shuffling required to reconfigure your system.

13214665c909842a1730051de668dc13d35f0156
