### ISSUE TITLE
Post-script missing db name ${4} when using ALL

### ISSUE THREAD

**Issue by mtompkins** [tiredofit/docker-db-backup#109]
### Summary

Custom script fails in respect to values as variable ${4} is no longer properly passed each iteration when using ALL.

### Steps to reproduce

execute custom post-script.

### What is the expected *correct* behavior?

The correct value of ${4}

With the recent changes and requirement of ALL, the call to post-script no longer provided the correct value of the database backup up (in other words ${4})

**Comment by tiredofit** [comment]
Hi Mark, 
Gah, I thought I solved that one yesterday - I'll go back at it and find out where I've made the mistake.

**Comment by mtompkins** [comment]
No worries / appreciate it. I post the outcome(s) to Slack like channel so I happened to catch it.

**Comment by tiredofit** [comment]
Darnit, missed your 10:30am watchtower rollover. New version `3.1.3` contains the fix - I had googly eyes and missed the MariaDB SPLIT_DB=TRUE section with yesterdays patchup. 

Also defaulted SPLIT_DB to TRUE like it was supposed to be and added some executable bit checking on the post scripts. Filename will get passed to the post script and also show properly on the console/file log.

**Comment by mtompkins** [comment]
Confirming the issue is resolved. Thanks as always.
