### ISSUE TITLE
Zabbix is enabled by default

### ISSUE THREAD

**Issue by elad-bar** [tiredofit/docker-db-backup#113]
### Summary

Zabbix Agent is enabled by default, it leads to lots of traffic,

### What is the expected *correct* behavior?
Same as all other configuration, it should be configured only if relevant,  

### Relevant logs and/or screenshots
```
2022-04-10.01:00:32 [NOTICE] ** [db-backup] Sending Backup Statistics to Zabbix
Sending failed. Use option -vv for more detailed output.
Sending failed. Use option -vv for more detailed output.
Sending failed. Use option -vv for more detailed output.
Sending failed. Use option -vv for more detailed output.
```
    
### Possible fixes
An alternative solution could be just to add a ENV to turn it off

**Comment by tiredofit** [comment]
See README about base images and turning off functionality.

**Comment by falkheiland** [comment]
as an extended answer (since i also ran into it):

Zabbix is activated in the base image by default (for whatever reason) so you have to disable it, if you do not (want to) use it.

```
xyz_db_backup.1.ypuckv4hmsnemxb28ke8cyzsg@sw2n2    | 2022-09-12.11:10:47 [STARTING] ** [monitoring] [10191] Starting Zabbix Agent (modern) 6.2.1
xyz_db_backup.1.ypuckv4hmsnemxb28ke8cyzsg@sw2n2    | sed: /etc/zabbix//zabbix_agentd.conf: No such file or directory
xyz_db_backup.1.ypuckv4hmsnemxb28ke8cyzsg@sw2n2    | sed: /etc/zabbix//zabbix_agentd.conf: No such file or directory
xyz_db_backup.1.ypuckv4hmsnemxb28ke8cyzsg@sw2n2    | sed: /etc/zabbix//zabbix_agentd.conf: No such file or directory
```

https://github.com/tiredofit/docker-alpine/#monitoring-options

add to your compose file:

```yml
CONTAINER_ENABLE_MONITORING=FALSE #Enable Monitoring of applications or metrics
```
