### ISSUE TITLE
POST_SCRIPT always says filesystem bit not executable.

### ISSUE THREAD

**Issue by CorneliousJD** [tiredofit/docker-db-backup#117]
Maybe I'm doing something wrong but when using the POST_SCRIPT option, I am simply turing to either curl or wget to a URL (healthchecks.io) to keep a monitor on my backups to make sure they actually fire off nightly.

It seems that it is not working via either of these three methods

`POST_SCRIPT: '/home/xxx/backup-healthcheck.sh'`
Which is just a .sh file to do the curl command or wget command, same as options below.
I have tried this with and without sudo.

The permissions of the file are  0755 - so everyone has execute access.

Direct commands in the post script also do not seem to work.

```
POST_SCRIPT: 'curl -m 10 --retry 5 https://xxx'
POST_SCRIPT: 'wget https://xxx -T 10 -t 5 -O /dev/null'
```

Everything ends up failing with

`[db-backup] Can't execute POST_SCRIPT environment variable '##########' as its filesystem bit is not executible!
`

How can I get this to run when backups kick off? Thank you!

**Comment by tiredofit** [comment]
Make sure your script is set to executible `chmod +x (yourscript)`. I used to perform this automatically but stopped for security purposes.

**Comment by CorneliousJD** [comment]
> Make sure your script is set to executible `chmod +x (yourscript)`. I used to perform this automatically but stopped for security purposes.

@tiredofit do the .sh for sure was +X'd in this. 
What about direct commands too, like curl or wget, they are also failing, is that expected? I would assume curl and wget are executable already but I am admittedly not super familiar with *nix at all, including permissions

**Comment by tiredofit** [comment]
You should be able to execute curl or wget from inside a script without issue - there are no barriers with that. 

In a future release I can add an environment variable to set it executable before starting. I'm assuming you are using Windows and this could be the root cause of this.  Alternatively to bind mounting a directory on your system to /assets/custom-scripts you could probably mount a named volume, which could resolve that issue?

**Comment by CorneliousJD** [comment]
> You should be able to execute curl or wget from inside a script without issue - there are no barriers with that.
> 
> In a future release I can add an environment variable to set it executable before starting. I'm assuming you are using Windows and this could be the root cause of this. Alternatively to bind mounting a directory on your system to /assets/custom-scripts you could probably mount a named volume, which could resolve that issue?

Hi @tiredofit  - so the device that's running this is an Ubutnu Server 20.04.4 LTS server running it as part of a docker-compose.yml file - My apologies for not including that in the original bug report. 

So it is running on linux right now and the 
`POST_SCRIPT: 'curl -m 10 --retry 5 https://xxx'`
unfortuantely did not work, and I would have thought that would work directly without issues.

I'll try mounting a bind mount and re-testing w/ my script there and making sure it's +x'd properly. I'll report back ;)

**Comment by CorneliousJD** [comment]
Ok it's working now - part of this was just my own stupidity, thank you for reminding me I need to have the script within a mounted volume. Whoops ;) 

I was first trying to curl directly within the POST_SCRIPT variable which wasn't working then when I made my script I never mounted it.  My config is as follow if this ever helps anyone else searching here.

  backups:
    image: tiredofit/db-backup
    container_name: backups
    volumes:
      - /home/xxx/backups:/backup
      - /home/xxx/scripts:/scripts
    restart: unless-stopped
    links:
      - db
    environment:
      TZ: 'America/Detroit'
      DB_TYPE: 'pgsql'
      DB_HOST: 'db'
      DB_NAME: 'xxx_xxx'
      DB_USER: 'postgres'
      DB_PASS: 'postgres'
      EXTRA_OPTS: '--schema=public --blobs'
      COMPRESSION: 'GZ'
      DB_DUMP_FREQ: '360'
      DB_DUMP_BEGIN: '+10'
      DB_CLEANUP_TIME: '10080'
      POST_SCRIPT: '/scripts/backup_complete.sh'

**Comment by tiredofit** [comment]
Glad you are sorted out! Will address your other issue soon - Just getting ready for a trip and will resolve in transit.
