### ISSUE TITLE
restore a db backup doesn't read port

### ISSUE THREAD

**Issue by Korvenwin** [tiredofit/docker-db-backup#121]
### Summary

When restoring a database backup with 'restore' command, all parameters are accepted until DBPORT that allways stays waiting.

### Steps to reproduce

Start a restore without parameters

### What is the expected *correct* behavior?

DBPORT should be accepted as others parameters.

### Environment

- Image version / tag:  v3.2.4
- Host OS: Unraid

**Comment by tiredofit** [comment]
Can you tell me if you actually have a value for `DB_PORT` ?

**Comment by Korvenwin** [comment]
Yes, 3306.

**Comment by tiredofit** [comment]
Thanks. Can you share a log of what happens so I can try to understand further?

Just interested in when it gets to the interactive DB_PORT section. 

Even better is if you could either run the restore command with CONTAINER_LOG_LEVEL=DEBUG, and even best would be if it could be run with DEBUG_MODE=TRUE however there is alot of output there. If not comfortable with sending the entire log here you can email me at dave at my github username dot ca .

**Comment by Korvenwin** [comment]
I'm using your docker on Unraid. 

With DEBUG_MODE=TRUE this is what I get:

`What Database Password will be used to restore?

    C ) Custom Entered Database Password
    E ) Environment Variable DB_PASS
    Q ) Quit

+ case "${q_dbpass_variant}" in
+ true
++ echo -e '\e[92m**' '\e[90mEnter' Value '(\e[97mC\e[90m)' '|' '(\e[97mE\e[90m)' : '\e[97m\e[0m'
+ read -p '** Enter Value (C) | (E) :  ' q_dbpass_menu
** Enter Value (C) | (E) :  e
+ case "${q_dbpass_menu,,}" in
+ r_dbpass='OQGE1#6A,#+vuKfvgSauX}IQy(bklfop'
+ break
+ print_debug 'Database Pass '\''OQGE1#6A,#+vuKfvgSauX}IQy(bklfop'\'''
+ output_off
+ '[' true = true ']'
+ set +x
2022-04-23.21:46:39 [DEBUG] /usr/local/bin/restore ** [db-backup-restore] Database Pass 'OQGE1#6A,#+vuKfvgSauX}IQy(bklfop'
+ '[' -n '' ']'
+ get_dbport
+ '[' -z 3306 ']'
+ '[' -n 3306 ']'
+ print_debug 'Parsed DBPort Variant: 2 - Env'
+ output_off
+ '[' true = true ']'
+ set +x
2022-04-23.21:46:39 [DEBUG] /usr/local/bin/restore ** [db-backup-restore] Parsed DBPort Variant: 2 - Env
+ q_dbport_variant=2
++ cat
+ q_dbport_menu='
    C ) Custom Entered Database Port
    E ) Environment Variable DB_PORT: '\''3306'\'''
+ cat

What Database Port do you wish to use? MySQL/MariaDB typcially listens on port 3306. Postrgresql port 5432. MongoDB 27017

    C ) Custom Entered Database Port
    E ) Environment Variable DB_PORT: '3306'
    Q ) Quit

+ case "${q_dbport_variant}" in
+ true
++ echo -e '\e[92m**' '\e[90mEnter' Value '(\e[97mC\e[90m)' '|' '(\e[97mE\e[90m)' : '\e[97m\e[0m'
+ read -p '** Enter Value (C) | (E) :  ' q_dbport_menu
** Enter Value (C) | (E) :  e
+ case "${q_dbname_menu,,}" in
+ true
++ echo -e '\e[92m**' '\e[90mEnter' Value '(\e[97mC\e[90m)' '|' '(\e[97mE\e[90m)' : '\e[97m\e[0m'
+ read -p '** Enter Value (C) | (E) :  ' q_dbport_menu
** Enter Value (C) | (E) :  e
+ case "${q_dbname_menu,,}" in
+ true
++ echo -e '\e[92m**' '\e[90mEnter' Value '(\e[97mC\e[90m)' '|' '(\e[97mE\e[90m)' : '\e[97m\e[0m'
+ read -p '** Enter Value (C) | (E) :  ' q_dbport_menu
** Enter Value (C) | (E) :  c
+ case "${q_dbname_menu,,}" in
+ true
++ echo -e '\e[92m**' '\e[90mEnter' Value '(\e[97mC\e[90m)' '|' '(\e[97mE\e[90m)' : '\e[97m\e[0m'
+ read -p '** Enter Value (C) | (E) :  ' q_dbport_menu
** Enter Value (C) | (E) :  `

**Comment by tiredofit** [comment]
Many thanks - `3.2.5` will fix this! I had haphazardly copied one of the functions and missed a step to rename. Let me know how this works.

**Comment by Korvenwin** [comment]
If it is possible, I would be very gratefull to you if I could get a 'beta' version. I need to recover urgently a data base.

**Comment by tiredofit** [comment]
Should be ready for you right now. Takes approx 5 minutes for it to build and be ready on the Docker Hub

**Comment by Korvenwin** [comment]
Restored sucessfully!!!!! Thank you very much for your great tool and better support.

**Comment by tiredofit** [comment]
Great! Thanks for helping debug and the logs.

**Comment by Korvenwin** [comment]
Hi again. This problem occurs again.
