### ISSUE TITLE
Backups fail

### ISSUE THREAD

**Issue by mtompkins** [tiredofit/docker-db-backup#124]
### Summary

Backups indicate success however they are 0 size.

Version:  Image: tiredofit/db-backup | Version 3.3.0

Relevant docker-compose settings:
```
environment:
      - DB_TYPE=mariadb
      - DB_HOST=mariadb
      - DB_NAME=ALL
      - DB_USER=root
      - DB_PASS=$MYSQL_ROOT_PASSWORD
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=+1
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=XZ
      - PARALLEL_COMPRESSION=FALSE
      - SPLIT_DB=TRUE
      - SIZE_VALUE=megabytes
```

**Comment by tiredofit** [comment]
Thanks for this, I'm able to confirm with XZ and understand what has happened with any backups made with `3.3.0` - I've just pushed a `3.3.1` which will get things back to normal!
