### ISSUE TITLE
Webhook to trigger alert in case backup failed

### ISSUE THREAD

**Issue by chrissi5120** [tiredofit/docker-db-backup#125]
**Description of the feature**
The Container should be able to notify its user of failing backup jobs, I suggest to use a webhook function for usage with sites like https://healthchecks.io/

**Benftits of feature**
The user can be confident in the success of his/her backup-jobs.
I just had an issue with the docker template as it suddenly stopped backing up due to a missing variable.
This or different reasons for failing backups (like missing user privileges, space, ...) can be alarmed long after the user regularly checks for the backups.

**Additional context**
Example integration: https://github.com/borgmatic-collective/docker-borgmatic/blob/408b0432f61c9beb4e5fa9dc8376edc5599f0a9e/ntfy/README.md
Based on: https://github.com/dschep/ntfy

**Comment by tiredofit** [comment]
Have a peek at the documentation regarding [custom scripts](https://github.com/tiredofit/docker-db-backup#custom-scripts).

You can take advantage of this information and use it to build your own payload and accomplish what you are trying to do. Curl is available inside the image for POSTs.
