### ISSUE TITLE
Post Backup Custom Script Support check fails at executable check

### ISSUE THREAD

**Issue by chrissi5120** [tiredofit/docker-db-backup#126]
### Summary

when you try to run a custom script under /assets/custom-scripts/post-script.sh it fails in its "### Post Backup Custom Script Support" - step (line 657)

### Steps to reproduce

create a custom script
place it under /assets/custom-scripts/post-script.sh
give script executable flag (e.g. chmod +x)
run "backup-now"
script fails 

### What is the expected *correct* behavior?

script should start

### Relevant logs and/or screenshots

2022-05-02.20:13:46 [ERROR] ** [db-backup] Can't run post backup custom script: '/assets/custom-scripts/post-script.sh' as its filesystem bit is not executible!

/assets/custom-scripts # ls -la post-script.sh 
-rwxrwxrwx    1 root     root           736 May  2 20:03 post-script.sh

test script with the following content runs fine on host-machine:

`#!/bin/bash
for f in $(find /some/path/ -name \*.sh -type f); do
            if [ -x "${f}" ] ; then
                echo "Executing post backup custom script : '${f}'"
            else
                echo "Can't run post backup custom script: '${f}' as its filesystem bit is not executible!"
            fi
        done
exit`

result:

Executing post backup custom script : '/some/path/test.sh'

### Environment

- Image version / tag:  tiredofit/db-backup             latest              758c4db22969 
- Host OS: unraid/slack

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

**Comment by tiredofit** [comment]
Thanks for this report. I'm unable to recreate on my system so I am wondering if there is something inconsistent between either our filesystems or host. The check for executible bit was added only recently (3.1.x ??) so this is interesting for me to hear. 

What I can do is add an environment variable to skip that check for you. This is in `3.3.2`
Set `POST_SCRIPT_SKIP_X_VERIFY=TRUE` and it will bypass the check running the scripts properly for you. If it doesn't still run it, then we have some issues at play here that I don't believe I would be capable of solving. Let me know..

**Comment by chrissi5120** [comment]
That worked like a charm, thank you!

2022-05-03.09:49:32 [NOTICE] ** [db-backup] Backup of xyz.sql.gz created with the size of 92130930 bytes
Backup Completed on host for all on 1651564163 ending 1651564172 for a duration of 9 seconds. Filename: filename.sql.gz Size:  bytes MD5: md5

I can't really wrap my head around that problem either, it seems as the bash check itself is broken (inside the container) for me..
even creating a replica of your script inside the container seems unable to determine the executable bit properly.

Again, thank you for your quick help!
