### ISSUE TITLE
Feature request: Backup individual DBs into different files for Postgres Databases.

### ISSUE THREAD

**Issue by upuldi** [tiredofit/docker-db-backup#129]
**Description of the feature**
Currently, all the DBs are backed up as a single file. Instead, make the DBs backed up into different files. The list of DBs can be provided as config/env variables.

**Benefits of feature**
Ability to restore the specific DB when required. 

**Additional context**

**Comment by tiredofit** [comment]
This exists already for certain DBs with the SPLIT_DB environment variable. You haven't listed with DB engine you are trying to back up?

**Comment by upuldi** [comment]
For Postgres DBs this is not working.

**Comment by tiredofit** [comment]
Feature in place for Postgresql for quite some time now. New release 4.0.0 includes support for a seperate authentication db vs a user db. https://github.com/tiredofit/docker-db-backup/releases/tag/4.0.0
