### ISSUE TITLE
TZ ENV not avaialbe

### ISSUE THREAD

**Issue by tamimology** [tiredofit/docker-db-backup#133]
**Description of the feature**
When I set DB_DUMP_BEGIN=0020, I was thinking it will be at 20 minutes past midnight my local time, I was surprised the next day it was not. It is on GMT local time, not mine.

There should be a TZ env set to have the dumping relative to that.

**Benftits of feature**
Makes dump scheduling more understandable and easy to configure

**Additional context**
N/A
![Screenshot from 2022-06-07 10-00-00](https://user-images.githubusercontent.com/90429593/172268354-bf9f5de6-3fa5-46d0-8277-20052fbd3c45.png)

**Comment by tiredofit** [comment]
See the [README](https://github.com/tiredofit/docker-db-backup#base-images-used) where it talks about the "other" variables available with the upstream base images. You'll find lots more switches to flick, including `TIMEZONE`
