### ISSUE TITLE
Docker Secrets: documentation and consistency

### ISSUE THREAD

**Issue by buxm** [tiredofit/docker-db-backup#138]
**Description of the feature**
I understand that this image supports for Docker secrets, e.g. instead of putting your DB password in the DB_PASS environment variable (which could be accessible outside of the container), put it into a "docker secret" that docker mounts as file in the container file system (e.g. /run/secrets/db_password) and set the env variable DB_PASS_FILE=/run/secrets/db_password. See https://docs.docker.com/engine/swarm/secrets/ for the why's and how to's of Docker secrets.

However I found the documentation about this feature lacking: i.e. no indication of which variable names can be used to point to secret files containing which parameter.
E.g.:
can I pass the DB name as a secret? Apparently no.
Can I pass the DB password as a secret? Yes.
Which variable contains the path to the secret file for the DB password? DB_PASS_FILE
The answers to these questions don't seem to be in the readme and are not straightforward.

Only digging through the code of [10-db-backup](https://github.com/tiredofit/docker-db-backup/blob/f005956c47464d2b7ae0acdbd9266a8efd8c0f1a/install/assets/functions/10-db-backup) I found out that the variable names that point to secret files use the `_FILE` suffix (which is common practice, but not dictated by Docker or by any official standard); and that they seem to be only `DB_USER_FILE`, `DB_PASS_FILE`, `S3_KEY_ID_FILE` and `S3_KEY_SECRET_FILE`.
Initially I was trying to use a secret also for the S3 bucket name, but having no success, I had to dig through the code to find out it wasn't me getting something wrong.

Also I am not sure why DB_USER_FILE is used for CouchDB, InfluxDB, MongoDB, but NOT for MySQL, PostgreSQL and Redis. This also came out when I was unsuccessful using a secret for the DB user for my MySQL DB and I had to dig through the code to understand why.

Suggestions:

1. document which variable can contain paths to secret files
2. if there is no technical issue unknown to me, extend the usage of `DB_USER_FILE` to al the other database types.

**Benefits of feature**
Documenting the "secrets" varialbe would make it easier for the user to get to know the support for Docker secrets and how to use it.

Making the DB username consistently "secret" across all DB types would improve security of implementation and also would make it easier for the user who don't need to know whethera specific secret can be used depending on DB type.

**Comment by samuk10** [comment]
` can I pass the DB name as a secret? Apparently no.`
looks like yes: 
`You can use secrets to manage any sensitive data which a container needs at runtime but you don’t want to store in the image or in source control, such as:

    Usernames and passwords
    TLS certificates and keys
    SSH keys
    Other important data such as the name of a database or internal server
    Generic strings or binary content (up to 500 kb in size)
`

**Comment by buxm** [comment]
Hi @samuk10,
yes the docker docs say they do support secrets. However support also needs to be built into the image. For example, in the same page, docker [says](https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images): 

> The WordPress image has been updated so that the environment variables which contain important data for WordPress, such as WORDPRESS_DB_PASSWORD, also have variants which can read their values from a file (WORDPRESS_DB_PASSWORD_FILE). This strategy ensures that backward compatibility is preserved, while allowing your container to read the information from a Docker-managed secret instead of being passed directly.

So essentially, in order to support secrets, docker images need to read from specific env variables which secret files they need to use for what, so that the user can set those variables with the name of the files where they put the corresponding secrets. What secrets to support (e.g. one for the password, one for the username, etc.) and what variable is supposed to hold their name is up to the image developer.

docker-db-backup appears to be supporting _some_ variables containing secret file names for _some_ secrets.
However which secrets are supported (e.g. db name, db user, db password, etc.) and the corresponding variable names are not currently clearly documented, as far as I can see. So the user struggles identifying which data they can put in secrets and which variables to populate accordingly.

Just as an example, the mariadb image readme clearly documents which secrets are supported in which variables in a [dedicated section](https://github.com/docker-library/docs/blob/master/mariadb/README.md#docker-secrets)

> [...]
`_FILE` may be appended to the previously listed environment variables
[...]
Currently, this is only supported for MARIADB_ROOT_PASSWORD, MARIADB_ROOT_PASSWORD_HASH, MARIADB_ROOT_HOST, MARIADB_DATABASE, MARIADB_USER, MARIADB_PASSWORD and MARIADB_PASSWORD_HASH (and MYSQL_* equivalents of these)

**Comment by samuk10** [comment]
got it!

**Comment by tiredofit** [comment]
`3.9.0` adds support and README is clear on what is supported by means of `_FILE` environment variables..
