### ISSUE TITLE
Postgres: no roles are backed up when SPLIT_DB is set

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-db-backup#139]
### no roles backed up
Postgres: 
when we use SPLIT_DB, the databases are backed up perfectly and could be restored. 
BUT: the roles and their passwords are not backed up.

Suggestion: run a  pg_dumpall -r after all backups.

**Comment by tiredofit** [comment]
Sure, that makes sense to me. Are you able to try `tiredofit/db-backup:develop` to see if it does what you are after?

You should see an additional file following the syntax of `pgsql_roles_(db_host)_(timestamp).sql.(yourcompressiontype)` post backup.

**Comment by joergmschulz** [comment]
this looks pretty good. The user info is there, the CREATE DATABASE not. My bad: I should have requested 
  pg_dumpall -g (same as --globals-only) instead.

**Comment by tiredofit** [comment]
No problem. I have a new `:develop` ready for a test.

**Comment by tiredofit** [comment]
Sure not a problem. I can add the -s easy enough.
I'm going to change the filenames and add a duplicate __ in front of the segment where the dbname is eg (pgsql__globals) and the schemas to avoid any conflicts. I'll add -s and push out a new release shortly.

**Comment by joergmschulz** [comment]
a restore to another machine worked using psql. The restore script told me psql wouldn't be possible. When this fine stuff is made public on github (no devel branch there), I can dig a bit. There are some databases to be migrated to another machine...
