### ISSUE TITLE
can i use one container to backup multiple databases (MariaDB ,PostgreSQL and etc ..)

### ISSUE THREAD

**Issue by masterwishx** [tiredofit/docker-db-backup#142]
i can use only one database to backup for one container ?
i cant backup all my databases (MariaDB ,PostgreSQL and etc ..)  right?
Thanks

**Comment by davrax** [comment]
Yeah I believe this requires 1 DB backup container for each db _host_ (if you run MySQL+PGSQL, you'd need two DB Backup containers)

**Comment by tiredofit** [comment]
Release 4.0.0 contains this long requested feature. https://github.com/tiredofit/docker-db-backup/releases/tag/4.0.0
