### ISSUE TITLE
Pre-Backup Custom Scripts

### ISSUE THREAD

**Issue by mark-monteiro** [tiredofit/docker-db-backup#153]
**Description of the feature**
Ability to add custom scripts to execute before a backup runs, in the same way the existing functionality allows custom scripts to execute after a backup.

**Benefits of feature**
I use healthchecks.io to monitor the status of my backup jobs. They have a feature to measure/display the execution time of tasks if you send a request before the task starts, and it would be nice to be able to integrate with that. See: https://healthchecks.io/docs/measuring_script_run_time/. It would be nice to be able to integrate with this feature.

**Additional context**
N/A

**Comment by tiredofit** [comment]
Hi there this has been added to version `3.4.0` . [Changelog](https://github.com/tiredofit/docker-db-backup/commit/dc4ab0bfc59f5c4580b2edc0ecfe19e57b168816) - Please read the README for the location to load Pre scripts from and let me know if you encounter any issues.

**Comment by mark-monteiro** [comment]
Wow, thanks for the fast turnaround! I'll let you know how it goes once I get a chance to update.

**Comment by mark-monteiro** [comment]
It looks like the pre-backup scripts are executed both at the start and end of the backup, which isn't good.

The path for pre-backup scripts (`/assets/custom-scripts/pre`) is a sub-folder of the one for post-backup scripts (`/assets/custom-scripts`), which is what causes this. Perhaps the [`find` arguments](https://github.com/tiredofit/docker-db-backup/blob/master/install/assets/functions/10-db-backup#L715) for the post-backup scripts can be altered to exclude this sub-folder?

I also noticed that the documentation in the README isn't quite right for the pre-backup scripts. Here's what I would change it to (I can open a PR to update this documentation if you'd like, or feel free to just take this change and commit it yourself):

    #### Pre Backup
    If you want to execute a custom script before a backup starts, you can drop bash scripts with the extension of `.sh` in `/assets/custom-scripts/pre`. See the following example to utilize:

    ````bash
    $ cat pre-script.sh
    ##!/bin/bash

    # #### Example Pre Script
    # #### $1=DB_TYPE (Type of Backup)
    # #### $2=DB_HOST (Backup Host)
    # #### $3=DB_NAME (Name of Database backed up
    # #### $4=BACKUP START TIME (Seconds since Epoch)
    # #### $5=BACKUP FILENAME (Filename)

    echo "${1} Backup Starting on ${2} for ${3} at ${4}. Filename: ${5}"
    ````

        ## script DB_TYPE DB_HOST DB_NAME STARTEPOCH BACKUP_FILENAME
        ${f} "${dbtype}" "${dbhost}" "${dbname}" "${backup_start_time}" "${target}"


    Outputs the following on the console:

    `mysql Backup Starting on example-db for example at 1647370800. Filename: mysql_example_example-db_202200315-000000.sql.bz2

**Comment by tiredofit** [comment]
Thanks for the feedback. I'm going to push a new version shortly and add environment variables to support changing the locations on where the post and pre scripts reside while also keeping the old `/assets/custom-scripts`. 

Should be less than 30 minutes here.

**Comment by tiredofit** [comment]
Alright. `3.4.1` contains the fix there.
I've introduced the following two environment variables:


| Parameter              | Description                                                                 | Default                 |
| ---------------------- | --------------------------------------------------------------------------- | ----------------------- |
| `SCRIPT_LOCATION_PRE`  | Location on filesystem inside container to execute bash scripts pre backup  | `/assets/scripts/pre/`  |
| `SCRIPT_LOCATION_POST` | Location on filesystem inside container to execute bash scripts post backup | `/assets/scripts/post/` |

I've added some routines to print a warning to allow people to migrate their post scripts to environment path they choose or the defaults. It will automatically copy the files from `/assets/custom-scripts/` into `SCRIPT_LOCATION_POST` and execute them.

Can you let me know how this one works? Just as a reminder you can type `backup-now` in a running container without having to wait for the timer to fire.

**Comment by mark-monteiro** [comment]
Just tested and it looks good to me!

I opened PR #158 to add some explicit migration instructions for the new script paths.

**Comment by tiredofit** [comment]
Great! Glad its worked out and sorry on the first release confusion!
