### ISSUE TITLE
README contains paths to incorrect custom scripts folder

### ISSUE THREAD

**Issue by ToshY** [tiredofit/docker-db-backup#154]
### Summary

README contains incorrect path for custom scripts: see [pre-backup](https://github.com/tiredofit/docker-db-backup#pre-backup) and [post-backup](https://github.com/tiredofit/docker-db-backup#post-backup) sections.

### Steps to reproduce

 `/assets/custom/pre` and `/assets/custom` resp.

### What is the expected *correct* behavior?

`/assets/custom-scripts/pre` and `/assets/custom-scripts` resp.
    
### Possible fixes

#155

**Comment by tiredofit** [comment]
Ahh thanks for this! I gapped out early in the morning putting this together.

**Comment by ToshY** [comment]
No problem 😉
