### ISSUE TITLE
postgres 15

### ISSUE THREAD

**Issue by simonmaris** [tiredofit/docker-db-backup#181]
It 's not possible to backup postgres 15 databases, since pg_dumpall is still at 14.5.

Can we update to postgres 15?

**Comment by simonmaris** [comment]
Did some digging: Alpine apk has not been updated yet, follow status here: 
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/40005

**Comment by tiredofit** [comment]
Postgresql 15 support is in place now, closing
