### ISSUE TITLE
minor bug. DB_TYPE="mariadb" reports successful backup

### ISSUE THREAD

**Issue by cdpb** [tiredofit/docker-db-backup#182]
### Summary

I am using your script(s) since a while. I didn't pay attention to the documentation and just exported DB_TYPE="mariadb".

docker exec into the backup container and `backup-now`. The backup was running successful with exit 0, even though there was no backup created. I checked the (excellent) documentation and of course, it needs to be DB_TYPE="mysql". Backup is running now. But some input validation would be actually good here.

### Steps to reproduce

docker exec ...
DB_TYPE="Iamaprettygirl-db" backup-now

### What is the expected *correct* behavior?

Throw error > 0

### Relevant logs and/or screenshots
 $ DB_TYPE="Iamaprettygirl-db" backup-now
** Performing Manual Backup
2022-11-15.18:00:12 [INFO] ** [db-backup] Backup routines finish time: 2022-11-15 18:00:12 GMT with overall exit code 0
2022-11-15.18:00:12 [NOTICE] ** [db-backup] Backup routines time taken: Hours: 0 Minutes: 00 Seconds: 00
2022-11-15.18:00:12 [INFO] ** [db-backup] Cleaning up old backups on filesystem

### Environment

- Image version / tag:  tiredofit/db-backup:3.5.5

I am happy to fix that myself, if I find the time.

**Comment by tiredofit** [comment]
Interesting! DB_TYPE is set to read for MySQL and variants to work for `mariadb` and `mysql`.

I have a feeling your quotes might be triggering it skipping MySQL/MariaDB , but I should also be erroring out if there is something not found. Let me look into this and add that functionality.

**Comment by tiredofit** [comment]
This has been resolved in `3.5.6` https://github.com/tiredofit/docker-db-backup/commit/22e126200ee266362c9f8885cd4fce62fd57c527 It will now error out if it doesn't understand the `DB _TYPE` variable

**Comment by cdpb** [comment]
Got to love open source. 
problem - report - fix

Thank you Dave
