### ISSUE TITLE
escaping errors

### ISSUE THREAD

**Issue by cdpb** [tiredofit/docker-db-backup#183]
### Summary

If you export DB_USER="foo" backups are not working, since the script expects DB_USER=foo and doesn't care about sanitizing the input.

### Steps to reproduce

- export alls envs in double quotes (")
- DEBUG_MODE=TRUE backup-now
- mysqladmin '-u"foo"' -P3306 '-h"db"' status
- there it hangs forever

### What is the expected *correct* behavior?

sanitize input so it's useable for the script.

### Environment

- Image version / tag:  tiredofit/db-backup:3.5.5
 
### Possible fixes
add function to sanitize all input

**Comment by tiredofit** [comment]
I would suggest not using double quotes - this came up a couple years ago regarding someone who actually was using the quotes. 

If creating an environment variable (ala docker compose) one does not need to quote. I believe there has only been one image of mine (OpenLDAP replication options) where I saw that it was needed but it was quite a few years ago. Can you let me know if that works once stripping the double quotes?

**Comment by cdpb** [comment]
I don't need to use double quotes, it's just a habbit.

I just double checked and single quotes escape everything nicely, in case someone is using special characters in there vars.

   `DB_USER='USERwithPROBLEMS$()!-;&' DEBUG_MODE=TRUE backup-now`
   `mysqladmin '-uUSERwithPROBLEMS$()!-;&' -P3306 -hdb status`

All good, case closed. Thanks :)
