### ISSUE TITLE
DB_CLEANUP_TIME doesn't work with blobxfer location

### ISSUE THREAD

**Issue by eoehen** [tiredofit/docker-db-backup#190]
# Problem

Cleanup of old backups doesn't work with `blobxfer`.

A code cleanup [commit](https://github.com/eoehen/docker-db-backup/commit/4e04e31d84c3497b00adf6e9d49d4cbe1b4bf042#diff-5e2954f9abcfee9f7dd93672770d3e518c463b3ad77160dcfed2c6b64b22f2d6L463), removes database cleanup process with `blobxfer`.

Should be:

```
case "${BACKUP_LOCATION,,}" in
                "file" | "filesystem" | "blobxfer" )
```

# Additional Feature 

Additional configuration value:

Add an environment variable to explicitly enable clean remote directory with `blobxfer`.

`BLOBXFER_REMOTE_CLEANUP` the default value is false.

When `BLOBXFER_REMOTE_CLEANUP ` is `true` the S3 storage should sync with `--delete --delete-only`.

**Comment by tiredofit** [comment]
I can't quite recall why I removed it from that case statement, but it was causing problems, which is how it ended up this way. What I will do is add another case option strictly for blobxfer and replicate a couple of the lines in filesystem which will also remove the if statement checking if BLOBxfer is there - I feel this will be cleaner and will introduce in next release.

**Comment by eoehen** [comment]
Don't worry!

I suspect this line was missing in original first version.
`if [ "${BACKUP_LOCATION,,}" = "blobxfer" ] ; then`

I like this variant because otherwise, the filesystem cleanup would have to be done in two places.
But it's your choice. Let me know if you want me to correct it and put it in its own option case. I can prepare it for you.

**Comment by eoehen** [comment]
I splitted 'blobxfer' cleanup in a own option case. #191

**Comment by tiredofit** [comment]
I swapped the branches from `master` to `main` around yesterday which closed your PR. I've included my own variant in `3.7.0` which should restore blobxfer syncing for you. Let me know..

**Comment by eoehen** [comment]
I have test it - cleanup works. You can close the issue for all I care. Thank you.

**Comment by tiredofit** [comment]
Great! Glad its working again, thanks for your contributions.
