### ISSUE TITLE
Add support for backing up mssql transactional log files

### ISSUE THREAD

**Issue by DistortedBit** [tiredofit/docker-db-backup#200]
---
name: Backing up mssql transactional log files
about: 

---

**Description of the feature**
Right now it only takes a full backup of the database. With this feature it will backup transactional logs. 

**Benftits of feature**
- This will allow minimal data loss in the event of database failure/corruption. 
- And this will also ensure that transaction logs are automatically truncated by mssql, which can grow 10s of gbs. 

Taking full backups every 15 minutes is not practical for fairly large databases. This way a full back up is taken every hour or every night. And every 15 minutes only new transactions are backed up. 

**Additional context**
This feature is already available in this repo [here](https://github.com/bbtsoftware/docker-mssql-backup/blob/84f322880a1bd13a6d4404c189b381ae21d94c4f/backup.sh#L38). The bash script is already there, just need to adopt it for this awesome image. 

I can test it out if someone can implement it.

**Comment by tiredofit** [comment]
Coming in upcoming version 4.x relase.
