### ISSUE TITLE
connecting to host database from docker container failing with host not accessible error.

### ISSUE THREAD

**Issue by kasakirankumar** [tiredofit/docker-db-backup#202]
Hi,
Backups are working fine when we create db & backup services created with compose file. But if we have DB installed in Host machine and want to take backups using this backup solution from container then not working.
N/w in compose file:
network_mode: host
    extra_hosts:
      - "host.docker.internal: 172.17.0.1"
      - "hostb: 127.0.1.1"

DB_HOST=localhost   (Env variable for mariadb), what should i mention here? tried multiple options but same error .
 [WARN] ** [db-backup] MySQL/MariaDB Server 'localhost' is not accessible, retrying..

https://medium.com/@jrperin1975/docker-accessing-host-database-49e1ff92a40#:~:text=In%20order%20for%20a%20docker,address%20to%20Docker's%20internal%20DNS.

followed above instructions, but still no luck.
Please suggest if i missed any n/w config. Thanks.

**Comment by kasakirankumar** [comment]
Issue Resolved

**Comment by BeKnowDo** [comment]
How did you resolve the issue...

**Comment by kasakirankumar** [comment]
Issue is with DB_HOST value. I am using vagrant VM for mariaDB, and provided Vagrant IP with **network_mode: host**  and issue got resolved. I have removed **extra_hosts** values.
