### ISSUE TITLE
No image >3.9.1 on container registries

### ISSUE THREAD

**Issue by buxm** [tiredofit/docker-db-backup#230]
Both [Docker Hub](https://hub.docker.com/r/tiredofit/db-backup) and [Github Container Registry](https://github.com/tiredofit/docker-db-backup/pkgs/container/docker-db-backup) do not appear to host images with tag >3.9.1. The `latest` tag was updated 1 month ago, corresponding to Release 3.9.1, so apparently there is no build for Releases 3.9.2 and 3.9.3.
Maybe some automation cog got stuck? Or did I miss any update about [prebuilt images](https://github.com/tiredofit/docker-db-backup#prebuilt-images)?

**Comment by tiredofit** [comment]
Interesting, looks like Github Actions has failed the last couple of builds - I am trying to rerun 3.9.3 right now. Github has had its share of reliability issues as of late and the last month has been hit or miss for their "Actions" CI system.

**Comment by benvia** [comment]
Take a look at the influxdb package. It is not found during the build of the image.

**Comment by tiredofit** [comment]
Thanks for this. `3.9.5` now building it manually.

**Comment by buxm** [comment]
@tiredofit I'm not sure if this means that `3.9.5` should be available on the container registries... but it's not there... still stuck with `3.9.1`.

**Comment by tiredofit** [comment]
Darn. Something is very indeed broken. I don't have much time to fix anything right now - what I will do is build something from my workstation and then upload for time being.

**Comment by tiredofit** [comment]
All fixed now. Sorry for delay.
