### ISSUE TITLE
Add --rsyncable to zstd

### ISSUE THREAD

**Issue by oscarsiles** [tiredofit/docker-db-backup#231]
**Description of the feature**
Currently it is only possible to have the --rsyncable argument for gzip files, but it is also supported by zstd.

**Benefits of feature**
Allow for smaller transfer deltas when using rsync or other backup solutions, while using zstd instead of gzip.

**Additional context**
N/A

**Comment by tiredofit** [comment]
Sure thing - very straight forward and easy to add. It's in the just released `3.9.4` tag.

**Comment by oscarsiles** [comment]
Not sure I see any changes to the actual code? Sorry if I missed something!

**Comment by tiredofit** [comment]
Looks like there was a problem with our CI, builds post 3.9.5 should have this in it now.
