### ISSUE TITLE
Documentation mismatch between repository README and Docker Hub page

### ISSUE THREAD

**Issue by dabico** [tiredofit/docker-db-backup#233]
Not a bug per se, but it might lead to incorrect configurations: the usage documentation in the `README.md` file of this repository is not in line with the one on the [Docker Hub page](https://hub.docker.com/r/tiredofit/db-backup/) of the image. I assume that the repository documentation is the right way of configuring the service, meaning that the guide on Docker Hub should be updated.

**Comment by tiredofit** [comment]
Thanks, looks like there was a broken link. I have updated the documentation to direct the user to this repository.
