### ISSUE TITLE
Blobxfer Feature Synchronize local storage before cleanup

### ISSUE THREAD

**Issue by eoehen** [tiredofit/docker-db-backup#235]
**Issue**

Local container storage is leading the way. Changes on the S3 storage are overwritten with the local state. Deletions or new files on the S3 storage are overwritten with the local status at the next backup upload by blobxfer. 
Changes on the S3 storage are lost.

If the container and volumes are completely rebuilt, in the worst case all backups on the S3 storage will be deleted. :-(

**Goal**

The S3 storage is supposed to be the leading storage.
New or deleted files on the S3 storage should be transferred to the local storage first.

**Implementation**

Before the new backup is copied to the local storage for synchronization, the local storage should be updated from the S3 storage.
This ensures that changes to the S3 storage are not lost. However, changes are taken into account again during cleanup.

The S3 storage is now the leading storage for the data and no longer the local storage.

**Comment by eoehen** [comment]
@tiredofit Do you have any question or feedback for this issue and pullrequest? Thank you.

**Comment by tiredofit** [comment]
Hi @eoehen I am just in the middle of working on a new version, and part of it is to review the PRs - This is one of them. I hope to look at it in the coming days.
