### ISSUE TITLE
not uploading backup to S3

### ISSUE THREAD

**Issue by BakasuraRCE** [tiredofit/docker-db-backup#245]
### Summary

Error on upload backup to S3

### Steps to reproduce

Use S3 option

### What is the expected *correct* behavior?

Uplaod the file

### Relevant logs and/or screenshots
```

tiredofit/db-backup:3.9.10 12:52:46 /] $ aws
Traceback (most recent call last):
  File "/usr/bin/aws", line 4, in <module>
    __import__('pkg_resources').run_script('awscli==1.25.97', 'aws')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```

### Environment

- Image version / tag:  3.3.10
- Host OS: Arch Linux
    
### Possible fixes
When i do `apk add py3-setuptools` into the container, was binary works again

**Comment by tiredofit** [comment]
Sorry about this - We started compiling AWS CLI in a recent release and this must have broke it. 

Going to investigate.

**Comment by tiredofit** [comment]
Not sure what I was thinking when I compiled `aws-cli` but I have now updated it to `2.13.9` which in my tests now is not throwing the python errors. Please, if you could move up to `tiredofit/db-backup:3.9.11` and see if things are working correctly?

**Comment by BakasuraRCE** [comment]
Hi! sure, but you still not updated the docker images, I only see 3.9.10

**Comment by tiredofit** [comment]
Looks like builds are failing on Github which is why they aren't appearing. Looking into..

**Comment by ToshY** [comment]
@BakasuraRCE FYI the current `latest` tag seems to be `3.9.11`, so could test with that 🙂

**Comment by tiredofit** [comment]
Rebuild the `3.9.11` tag...

**Comment by BakasuraRCE** [comment]
thanks guys! Its working now
