### ISSUE TITLE
issue with Connecting MSSQL

### ISSUE THREAD

**Issue by killmasta93** [tiredofit/docker-db-backup#255]
### Summary

Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Client unable to establish connection.

Error code 0x2746.

### Steps to reproduce

/opt/mssql-tools18/bin/sqlcmd -C -S 192.168.0.3,1433 -U test2 -P thepassword

reading a bit seems that openSSL is using version 3 not sure how i can downgrade it?

Thank you

**Comment by tiredofit** [comment]
Newest versions should be working now with an updated MSSQL library.
