### ISSUE TITLE
Add the possibility to set the --drop argument for mongorestore

### ISSUE THREAD

**Issue by thomas-negrault** [tiredofit/docker-db-backup#259]
**Description of the feature**

When using `mongorestore`, it only inserts missing documents (i.e.: a document in the backup but not in the database) using the `_id` of the document. So if an _id is existing, the mongorestore skip it.

This means that when restoring a backup, newly created documents will still be there, and existing documents will not be restored back to their state at the backup time.

This is the expected behavior, as the [documentation](https://www.mongodb.com/docs/database-tools/mongorestore/#insert-only) explains:

> Insert Only
> mongorestore  can create a new database or add data to an existing database. However, mongorestore performs inserts only and does not perform updates. That is, if restoring documents to an existing database and collection and existing documents  have the same value _id field as the to-be-restored documents, mongorestore will not overwrite those documents.

To "prevent" this and have a "real" backup/restore mechanism, where the full database is back the way it was at the time of the backup, we can use the [`--drop`](https://www.mongodb.com/docs/database-tools/mongorestore/#std-option-mongorestore.--drop) option.

I am thinking of several options:

- create an env variable like `MONGO_RESTORE_DROP` that would be false by default but could be enabled
- ask during the restore script if it should drop or not
- create an env variable that would contain additional arguments for the mongorestore command. That way if someone has the need to add another argument like `--dryRun` or anything, there will be no need to add another env variable. The variable could be `MONGO_RESTORE_ARGUMENTS` and could be used like: `MONGO_RESTORE_ARGUMENTS=--dryRun --drop`

What do you think ? (If it's one of the 2 solutions with an env variable, I can make the PR)

**Comment by tiredofit** [comment]
I think I could quickly insert a Y/N question before restoring the mongodb to perform a drop before. Let me try this.

**Comment by tiredofit** [comment]
Have a peek at `3.10.5` for a new question asked before restore to drop the existing data. Found another not important glitch in the restore limiting ability to manually choose MongoDB when picking a file..

https://github.com/tiredofit/docker-db-backup/commit/d5cacdb32ad3958d587693b141572953ba0c7338
