### ISSUE TITLE
Release 3.12.0 does not have changes made in PR #263

### ISSUE THREAD

**Issue by alwynpan** [tiredofit/docker-db-backup#265]
### Summary

Release 3.12.0 does not have changes made in PR #263

### Steps to reproduce

`docker run --rm tiredofit/db-backup:3.12.0 bash -c "cat assets/functions/10-db-backup | grep authdb"`

### What is the expected *correct* behavior?

Should see code related to change made in PR #263 

### Relevant logs and/or screenshots

`  authdb=${DB_USER}
        db_names=$(psql -h ${DB_HOST} -U ${DB_USER} -p ${DB_PORT} -d ${authdb} -c 'COPY (SELECT datname FROM pg_database WHERE datistemplate = false) TO STDOUT;' )
        tmp_db_names=$(psql -h ${DB_HOST} -U ${DB_USER} -p ${DB_PORT} -d ${authdb} -c 'COPY (SELECT datname FROM pg_database WHERE datistemplate = false) TO STDOUT;' )`

~~By looking at the git history, it looks like since `v3.10.5`, the changes were left out in the releases.~~

<img width="1243" alt="image" src="https://github.com/tiredofit/docker-db-backup/assets/9387800/80f6e015-6f74-43af-906a-7a6f96c01bb0">

### Environment

- Image version / tag:  
- Host OS:

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

**Comment by alwynpan** [comment]
Thanks @tiredofit . It seems you are online 24/7 🥇

**Comment by tiredofit** [comment]
I actually dont ever remember seeing that line to be honest? I branched at 3.12.0 to branch `4.x` and looking at the history there it seems to look the same. Have a peek here: 

https://github.com/tiredofit/docker-db-backup/commits/4.x?after=89e6956cdd87c79b52908c3fd912e0784aae3bcc+34&branch=4.x&qualified_name=refs%2Fheads%2F4.x

**Comment by alwynpan** [comment]
Looking at the git history graph, it seems the changes are left out when you tagged `3.12.0`

<img width="1109" alt="image" src="https://github.com/tiredofit/docker-db-backup/assets/9387800/b271898f-b4ed-4ce1-bbea-983d3dc794f8">

**Comment by tiredofit** [comment]
Something certainly has happened to the main branch and I'm not sure what..
Do you happen to have a copy of your branch I can look at again?
I'm currently focusing on getting the 4.x release ready and will manually insert them into the codebase as its essentially a rewrite.

**Comment by alwynpan** [comment]
this is the commit: 82eac9ad2eeafe786d720909c5d7a87513a92d56

My branch was a goner, it has been deleted when the PR was merged.

**Comment by alwynpan** [comment]
I think I know what has happened. I believe to fix, just remove the tag from the red arrow and apply to the green one

<img width="1109" alt="image" src="https://github.com/tiredofit/docker-db-backup/assets/9387800/bb53c9bd-e2bb-4fa3-9247-4d42d67ccdd7">

**Comment by tiredofit** [comment]
OK I've retagged `3.12.0` let me know if this looks good for you?

**Comment by alwynpan** [comment]
Sorry for the late response. I was away for the weekend. I just tested with the new image and can confirm it is working. Thank you again @tiredofit
