### ISSUE TITLE
Version 4.0.0 Variable DEFAULT_S3_HOST/DBxx_S3_HOST seems to be broken

### ISSUE THREAD

**Issue by PinguCloud** [tiredofit/docker-db-backup#267]
### Summary

In Version 4.0.0 it is not possible to use a S3/B2 host like Backblaze because the relevant variable seem to be ignored.

### Steps to reproduce

Set a different S3-Host, e.g.:

      - DEFAULT_S3_BUCKET=Dummy-Bucket
      - DEFAULT_S3_KEY_ID=Dummy-Key
      - DEFAULT_S3_KEY_SECRET=Dummy-Secret
      - DEFAULT_S3_REGION=eu-central-003
      - DEFAULT_S3_PATH=boockstack
      - DEFAULT_S3_HOST=s3.eu-central-003.backblazeb2.com

The logs indicate that the backup is tried to be moved to amazonaws instead of backblaze.

### What is the expected *correct* behavior?

Upload to Backblaze instead of Amazon.

### Relevant logs and/or screenshots

Could not connect to the endpoint URL: "https://s3.eu-central-003.amazonaws.com/Dummy-Bucket/boockstack/mysql_bookstack_192.168.0.21_20231109-111912.sql.zst.md5"

### Environment

- Image version / tag:  4.0.0
- Host OS: Ubuntu-Server 22.04

**Comment by tiredofit** [comment]
Thanks for the report. I believe I missed a variable when porting over to the new format to support multiple hosts.

There is a new debug statement `DEBUG_MOVE_DBBACKUP` that should only expose the information related to your moving of the file to S3 which may uncover some information. 

In the meantime I believe `4.0.2` is going to get your backups working again. Please let me know?

**Comment by PinguCloud** [comment]
Thank you so far! I will check back tomorrow and test 4.0.2.

**Comment by PinguCloud** [comment]
It's working now. Thank you very much! :)
