### ISSUE TITLE
Version 4.0.0 "Restore" does not find any backups 

### ISSUE THREAD

**Issue by PinguCloud** [tiredofit/docker-db-backup#268]
### Summary

No backups are found, because "options" still use old variable "DB_DUMP_TARGET".

### Steps to reproduce

Try to restore in version 4.0.0

### What is the expected *correct* behavior?

Find created backups.

### Relevant logs and/or screenshots

[tiredofit/db-backup:4.0.0 12:02:18 /] $ restore
+ source /assets/defaults/10-db-backup
++ BACKUP_JOB_CONCURRENCY=1
++ DEFAULT_BACKUP_BEGIN=+0
++ DEFAULT_BACKUP_INTERVAL=60
++ DEFAULT_BACKUP_INTERVAL=60
++ DEFAULT_BACKUP_LOCATION=FILESYSTEM
++ DEFAULT_BLOBXFER_REMOTE_PATH=/docker-db-backup
++ DEFAULT_CHECKSUM=MD5
++ DEFAULT_COMPRESSION=ZSTD
++ DEFAULT_COMPRESSION_LEVEL=3
++ DEFAULT_CREATE_LATEST_SYMLINK=TRUE
++ DEFAULT_ENABLE_PARALLEL_COMPRESSION=TRUE
++ DEFAULT_ENCRYPT=FALSE
++ DEFAULT_FILESYSTEM_PATH=/backup
++ DEFAULT_FILESYSTEM_PERMISSION=700
++ DEFAULT_FILESYSTEM_ARCHIVE_PATH=/backup/archive/
++ DEFAULT_LOG_LEVEL=notice
++ DEFAULT_MYSQL_ENABLE_TLS=FALSE
++ DEFAULT_MYSQL_EVENTS=TRUE
++ DEFAULT_MYSQL_MAX_ALLOWED_PACKET=512M
++ DEFAULT_MYSQL_SINGLE_TRANSACTION=TRUE
++ DEFAULT_MYSQL_STORED_PROCEDURES=TRUE
++ DEFAULT_MYSQL_TLS_CA_FILE=/etc/ssl/cert.pem
++ DEFAULT_MYSQL_TLS_VERIFY=FALSE
++ DEFAULT_MYSQL_TLS_VERSION=TLSv1.1,TLSv1.2,TLSv1.3
++ DEFAULT_MSSQL_MODE=database
+++ nproc
++ DEFAULT_PARALLEL_COMPRESSION_THREADS=12
++ DEFAULT_RESOURCE_OPTIMIZED=FALSE
++ DEFAULT_S3_CERT_SKIP_VERIFY=TRUE
++ DEFAULT_S3_PROTOCOL=https
++ DEFAULT_SCRIPT_LOCATION_PRE=/assets/scripts/pre/
++ DEFAULT_SCRIPT_LOCATION_POST=/assets/scripts/post/
++ DEFAULT_SIZE_VALUE=bytes
++ DEFAULT_SKIP_AVAILABILITY_CHECK=FALSE
++ DEFAULT_SPLIT_DB=TRUE
++ LOG_PATH=/logs
++ MANUAL_RUN_FOREVER=TRUE
++ MODE=AUTO
++ TEMP_PATH=/tmp/backups
++ '[' -n '' ']'
+ source /assets/functions/10-db-backup
+ PROCESS_NAME=db-backup-restore
+ oldcolumns=
+ cdgy='\e[90m'
+ clg='\e[92m'
+ clm='\e[95m'
+ cwh='\e[97m'
+ coff='\e[0m'
+ bdr='\e[41m'
+ bdg='\e[42m'
+ bdb='\e[44m'
+ bdm='\e[45m'
+ bdgy='\e[100m'
+ blr='\e[101m'
+ boff='\e[49m'
+ bootstrap_variables
+ var_true ''
+ '[' '' = true ']'
+ '[' '' = yes ']'
+ case "${1}" in
+ var_true ''
+ '[' '' = true ']'
+ '[' '' = yes ']'
+ '[' -z '' ']'
+ interactive_mode=true
+ cat

## ####################################################

+ '[' -n '' ']'
+ get_filename
+ COLUMNS=12
+ prompt='Please select a file to restore:'
+ options=($(find "${DB_DUMP_TARGET}" -type f -maxdepth 1 -not -name '*.md5' -not -name '*.sha1' -print0 | sort -z | xargs -0))
++ find '' -type f -maxdepth 1 -not -name '*.md5' -not -name '*.sha1' -print0
++ sort -z
++ xargs -0
find: : No such file or directory
+ PS3='Please select a file to restore: '
+ select opt in "${options[@]}" "Custom" "Quit"
1) Custom
2) Quit
Please select a file to restore: 

### Environment

- Image version / tag:  4.0.0
- Host OS: Ubuntu Server 22.04

    
### Possible fixes

Update variable for restore function.

**Comment by tiredofit** [comment]
`4.0.1` now looks for the `DEFAULT_BACKUP_PATH`. In future versions restore will handle multiple hosts better, for now it's still a bonus script to reduce restore friction for common use cases..

**Comment by tiredofit** [comment]
`4.0.4` now supports detection of multiple environment variables :)

**Comment by PinguCloud** [comment]
Awesome, thanks! :)
