### ISSUE TITLE
log data not sent to zabbix

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-db-backup#278]
Looking at 
``` silent run_as_user zabbix_sender -c "${ZABBIX_CONFIG_PATH}"/"${ZABBIX_CONFIG_FILE}" -i "${zabbix_payload}" ``` 
I see that after backing up, data should be sent to zabbix, but they aren't.:
```  
[ERROR] ** [01-postgres-db__ALL] Error sending statistics, consider disabling with 'CONTAINER_ENABLE_MONITORING=FALSE' 
```

When setting 
```
export ZABBIX_CONFIG_PATH=/etc/zabbix
export ZABBIX_CONFIG_FILE=zabbix_agentd.conf
``` 

data are sent to zabbix.
Obviously, the envvars arent't set automatically in the image.

**Comment by tiredofit** [comment]
Odd, I've got a couple hundred backing up.

Have you changed out to the new template?

Can you try `DEBUG_POST_BACKUP=TRUE` and see whats happening?
Also `SHOW_OUTPUT=TRUE` might be useful..

**Comment by joergmschulz** [comment]
using the .14 version helps - this error is gone, it's no longer necessary to specify the config file name.
