### ISSUE TITLE
MYSQL_PASS_STR erroneous

### ISSUE THREAD

**Issue by hrrbrt** [tiredofit/docker-db-backup#28]
Connection to mysql database not possible, but when changing the MYSQL_PASS_STR from

            [[ ( -n "${DB_PASS}" ) ]] && MYSQL_PASS_STR=" -p'${DBPASS}'"

to

            [[ ( -n "${DB_PASS}" ) ]] && MYSQL_PASS_STR=" -p${DBPASS}"

all works fine

**Comment by tiredofit** [comment]
We recently made a change to wrap them in quotes - By chance does your password contain any special characters in it?

**Comment by hrrbrt** [comment]
No special characters in my password, only characters and numbers. My feeling is that the functions 'backup_mysql()' and 'check_availability' handle things differently. If I set DB_PASS to "Password", check_availability failed, removing the double quotes then made backup_mysql() fail. Could it be that as it stands, the script for 'mysql' doesn't work whatever password is used?

**Comment by tiredofit** [comment]
Thanks. To look into today - I'm not seeing this sort of activity on my end and running a couple dozen of these containers. It's very much possible something has broken when I altered the base images, in some of my other projects quite a few quirks have popped up- Will see what I can find.

**Comment by tiredofit** [comment]
See `tiredofit/db-backup:1.18.2` for the fix, please confirm we're back on track!

**Comment by hrrbrt** [comment]
Thanx, I'll do so until tomorrow and give feedback
