### ISSUE TITLE
Cleanup not running in 4.0

### ISSUE THREAD

**Issue by megatwig** [tiredofit/docker-db-backup#281]
### Summary

`cleanup_old_data()` is no longer called as part of the backup routine.

Automatic cleanup that worked fine under v3 stopped working since v4. I realised when a disk ran out of storage from being filled up with database backups that had stopped being cleaned up. I tried changing my old environment variable from `DB_CLEANUP_TIME` to `DEFAULT_CLEANUP_TIME`, and also `DB01_CLEANUP_TIME` to no effect. No logs in the console about cleanup running.

The `cleanup_old_data` function no longer appears to be referenced anywhere in this repo, so I guess the step got accidentally dropped from the backup script when it was migrated.

**Comment by tiredofit** [comment]
Wow - this is embarrassing that I omitted this. Fixed in `4.0.15`
https://github.com/tiredofit/docker-db-backup/commit/34abe8815903f1e9cbc35568fe96ff3cfd81fe7f

**Comment by JvdMaat** [comment]
Updating now. I just noticed the same lack of cleanup as my disk is now at 90%. Thanks!
