### ISSUE TITLE
DB_HOST vs DEFAULT_HOST

### ISSUE THREAD

**Issue by benvia** [tiredofit/docker-db-backup#285]
### Summary

Using DEFAULT_HOST parameter for database server hostname is not working. Use DB_HOST parameter instead works.

This is not clear in documentation or this is not how it's supposed to work.

### Environment
- Image version / tag:  4.0.18

**Comment by tiredofit** [comment]
DEFAULT_HOST along with DEFAULT_NAME, DEFAULT_USER, DEFAULT_PASS, and DEFAULT_PORT don't exist. 

DEFAULT_HOST is a special one as that is what I use to count the multiple instances and generate the schedulers..
