### ISSUE TITLE
Backup Location Permissions getting wipe out

### ISSUE THREAD

**Issue by Andy2728** [tiredofit/docker-db-backup#286]
### Summary

Once the backup runs, the unraid file permissions are stripped away. This affects the next part of my backup process, as the permissions are getting stripped my other software cannot see the files.

It didn't use to do this a few weeks ago though and nothing has changed within my configurations just a container update. So thought I would see here before doing anything drastic and changing things.

### Steps to reproduce

Install Container into unRAID.
Setup to backup MYSQL DB Container from unRAID.
Setup Path to, in this case: /mnt/user/databasebackups/mySQL/
The folder has OWNER set to NOBODY and the following Permissions: drwxrwxrwx

![image](https://github.com/tiredofit/docker-db-backup/assets/32003845/6b524af3-290e-4098-8dcc-f548d8640517)

After the CRON job runs and it backups up MYSQL, The file permissions on the mySQL folder and dump files have an owner: UNKNOWN and the following file permissions -rw---------

![image](https://github.com/tiredofit/docker-db-backup/assets/32003845/663b0f17-a6bc-40f4-b0cc-02626c357c93)

### What is the expected *correct* behavior?

I would think it should keep the existing file permissions as it use to?

### Environment

docker run
  -d
  --name='db-backup'
  --net='bridge'
  -e TZ="Australia/Brisbane"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="unRAID"
  -e HOST_CONTAINERNAME="db-backup"
  -e 'COMPRESSION'='GZ'
  -e 'DB_NAME'='ALL'
  -e 'DB_TYPE'='mysql'
  -e 'DB_HOST'='10.1.1.8'
  -e 'DB_USER'='root'
  -e 'DB_PASS'=''
  -e 'DB_PORT'='3306'
  -e 'DB_DUMP_FREQ'='1440'
  -e 'DB_DUMP_BEGIN'='0808'
  -e 'DB_CLEANUP_TIME'='10080'
  -e 'PARALLEL_COMPRESSION'='TRUE'
  -e 'MD5'='TRUE'
  -e 'SPLIT_DB'='FALSE'
  -e 'DEBUG_MODE'='false'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/db-backup.png'
  -v '/mnt/user/databasebackups/mySQL/':'/backup':'rw' 'tiredofit/db-backup:latest'
1ecf97da7346e1d7d958367c2e1e21e8bd06500df051d3b8f93c2e0eec02422d

- Image version / tag:  latest
- Host OS: unRAID 6.12.4

**Comment by tiredofit** [comment]
You've upgraded to a newer version by using `:latest`. Check the README and changelogs.
