### ISSUE TITLE
--Feature Request-- call apprise

### ISSUE THREAD

**Issue by bd8392** [tiredofit/docker-db-backup#29]
Hi :-) I just wanted to ask if it would be possible to integrate an apprise api-call with the backup-status (sucess/failure) to monitor :-) I can help with integration :-) here is a tutorial of mine, how it worked on duplicati :-) https://forum.duplicati.com/t/duplicati-and-telegram/6282/18

And here how it was integrated to shepherd:
djmaze/shepherd#30

Hope that helps :-) if you need more, just tell me :-)

**Comment by tiredofit** [comment]
I have a bit on my queue for things to do but something like this is possible. Looking at how Apprise communicates it can be triggered by some sort of script and using curl, so what I'm toying around with is allowing custom scripts to be executed after the backup completes. This way you could mount your own custom script that is called by the backup image with a bunch of variables (date, time, name of backup, type of db, filename) and pass that onto whatever external system you want. Sound good?

**Comment by bd8392** [comment]
YES =))) This is perfect =) Thank you =) I can show you how duplicati has achieved it =) Maybe it eases your work =)
https://forum.duplicati.com/t/duplicati-and-telegram/6282/19

**Comment by bd8392** [comment]
I was able to test your container and it's really cool =). I've some additional ideas for the notification =). I've seen that your container creates md5 (which is really usefull!). For the notification it would be great if the container can compare the md5 and send the result in an environment variable =). By the way - your container works perfectly in swarm! really cool!

**Comment by tiredofit** [comment]
See Release `tiredofit/db-backup:1.19.0` for custom script support.
`README.md` details how to use and there is also an example in the `examples` folder.

**Comment by bd8392** [comment]
Okay i've seen the docs and tried to put it in the /backups directory of your container, but this doesn't work (got no logs about it)...The docs only mention "this" directory, but I couldn't figure out which directory is meant...

**Comment by tiredofit** [comment]
`/assets/custom-scripts/`  - Sorry, it should be in the volumes section of the README

**Comment by bd8392** [comment]
Okay thanks I'll test it =)

**Comment by tiredofit** [comment]
I also just realized the README is a bit squirrelly due to a malformed backtick. I will resolve immedaitely.

**Comment by bd8392** [comment]
It Works! =). there are only some problems with the variables when using root-user for mariadb backups:
1) The Filename-Variable doesn't display all database names when you split them, but the first one it backups
2) The Database-name-Variable doesn't show a single value when backing up multiple databases with split-option
3) The MD5 Value isn't compared, but displayed (which is just a bunch of numbers not usable for monitoring)
4) The status of the backup (succes/failure/error) is not available for display

Here is a sample-apprise sidecar used:
```
version: '3.3'
services:
  apprise:
    image: caronc/apprise:latest
    networks:
     - net
    logging:
      driver: json-file
networks:
  net:
    driver: overlay
    driver_opts:
      opt: encrypted
```
Be careful to connect the db-backup container to the notifier net!

With this script used (in my tests I've used all your provided variables, but for this example, it's stripped down a little bit). It's an ugly one-liner because of json
```
#!/bin/bash
curl -s -X POST -d "{\"urls\":\"tgram://someapikey/somechatid\", \"body\":\"${1} Backup completed on ${2} at ${4} ${5}.\", \"title\":\"MariaDB_Backup_EXAMPLE\"}" -H "Content-Type: application/json" http://apprise:8000/notify
exit 0
```
also the output of the script does not appear in logs...
Everything else works perfect =)

**Comment by bd8392** [comment]
> I also just realized the README is a bit squirrelly due to a malformed backtick. I will resolve immedaitely.

I've discovered that this command doesn't work for me...maybe something wrong with it?:
```
docker exec -it (whatever your container name is e.g.) db-backup bash

**Comment by tiredofit** [comment]
- 1. 2Right, I expected some SPLIT_DB and root issues - I generally try to avoid using those variables and stick with one container to one db, but made it possible to backup all. I'll have to hack away at those routines to come up with a way to send multiple notifications / calls to the post script, although things are going to get ugly. Will go at it again in a few days.

3. I'm not sure I follow the MD5 Sum comparison statement though, can you explain what you would be after? I think I'd just need to understand a use case. Personally I don't use the MD5 Sum until restoring.

4. At this stage not capturing those error codes coming out of systems, as each of the tools don't output proper exit codes. One dirty hack I can implement is to base it on the size of the exported filename, however that is really not a true SUCCESS/FAIL/STATUS. I have my own monitoring system letting me know if there are errors if the size is more than 20% than the previous days, but that is not something related to the image itself. If you find similar scripts out there being able to capture proper success/fail statuses I'd be more than willing to review and see if I can work into future revisions.

I think with the custom script, you may have to tell it to output content for debugging on your own. Try that with a `set -x` at the top of your script below `#!/bin/bash`

**Comment by bd8392** [comment]
Ad 1) would'nt it be easier to just put the output of the console after the backup started, into a variable? That output is perfect because it shows all the backuped databases :-)

Ad 3 and 4) I've expected the md5 sum is made before backing up the database of the original one (as it reads it for backup). Then the md5 is made of the backup-file (so you can verify backup-integrity). If both values match, the backup is successful. If not, there is an error/failure output...maybe this approach would kill both problems at once if this is possible :-)

**Comment by bd8392** [comment]
Should we open an new issue on the above discussion? Because calling apprise is working now :-)
