### ISSUE TITLE
No Backups Created - errors in PostgreSQL logs

### ISSUE THREAD

**Issue by Tyree** [tiredofit/docker-db-backup#291]
Backups of MySQL server in separate container work fine. Instance for Postgres fails. Postgres logs say:
```
2023-11-21 03:00:00.852 EST [535] FATAL:  password authentication failed for user "dbbackup"
2023-11-21 03:00:00.852 EST [535] DETAIL:  Role "dbbackup" does not exist.
        Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
2023-11-21 03:00:00.872 EST [536] FATAL:  database "admin" does not exist
```
But DB_NAME and DB_USER are not set to those values. So where is it getting that from?

The login credentials the container has are correct and work fine to log in via Adminer.

If I run backup-now in the container terminal, I get this:
`psql: error: connection to server at "192.168.75.10", port 5432 failed: FATAL:  database "admin" does not exist`
Are the keys in the template wrong for postgreSQL?

**Comment by Tyree** [comment]
Manual run with debug mode on show this as the query sent:
`psql -h 192.168.75.10 -U admin -p 5432 -d admin -c 'COPY (SELECT datname FROM pg_database WHERE datistemplate = false) TO STDOUT;'`
Looks like it's set the port number as the password and the username as the database.
Attaching my settings. It looks correct, but it doesn't seem the script is parsing it correctly.
![settings](https://github.com/tiredofit/docker-db-backup/assets/5395363/dd82b459-a4f7-439a-81f1-87b762a52473)

**Comment by Tyree** [comment]
Tried it all on a different unRAID server. Same error. It comes back saying database "<username>" does not exist.
There is something broken in how the query is parsed from the container variables. They don't work the same from mysql to pgsql.

**Comment by alwynpan** [comment]
@Tyree please see this: https://github.com/tiredofit/docker-db-backup/issues/262, it was fixed in https://github.com/tiredofit/docker-db-backup/issues/263

**Comment by Tyree** [comment]
Do I have to use the authdb in order for this to work, or should it work by just providing the username, password, and db name?

**Comment by alwynpan** [comment]
Yes, you have to specify the authdb as pgdump  assumes a database with the same name as the $DB_USER exists.

**Comment by Tyree** [comment]
@alwynpan Forgive my ignorance here, please.
Is that as simple as creating a database with the same name as $DB_USER?

**Comment by alwynpan** [comment]
@Tyree when you create a PGSQL container, if $POSTGRES_DB is not specified, the container will use the value of $POSTGRES_USER by default. However, if you specify a $POSTGRES_DB,  a database with that name will be created.

When authorizing, PGSQL assumes a database with the same name as the user exists and use it as the authdb. However, if you created a database with a different name, then you have to specify the authdb otherwise you won't be able to connect to the database.

**Comment by Tyree** [comment]
Got it. That's what I ended up doing. I redid all the keys in the unRAID template to match that on the github docs and then added the DB01_AUTHDB key. That fixed it up and it's working fine now.
Thanks for your help!
