### ISSUE TITLE
[MariaDB] Unknown column 'generation_expression' in 'field list' (1054)

### ISSUE THREAD

**Issue by k3rn3l3rr0r** [tiredofit/docker-db-backup#295]
### Summary

Getting error 1054 - "Unknown column 'generation_expression' in 'field list' (1054)" from mysqldump while trying to backup MariaDB databases. The backup results (correctly) into one file per defined database on the server. The resulting backup file always contains only the schema definition of the (alphabetically) first table.  No errors are reported and the dump ends with exit code 0, but the resulting backup is incomplete and useless.

### Steps to reproduce

1. set up backup job of type DB01_TYPE=mariadb and DB01_NAME=ALL
2. run container and access its bash
3. start manual backup with "backup-now" command

### What is the expected *correct* behavior?

The resulting backup files should contain schema and content/data of all tables contained in each database defined on the server.

### Relevant logs and/or screenshots

```
+ + pigz -q -3 -p 24run_as_user mysqldump --max-allowed-packet=512M -h 
mariadb -P 3306 -uroot --events --single-transaction --routines redacted
+ + sudo run_as_user tee -Eu dbbackup mysqldump /tmp/backups/mysql_redacted_mariadb_20231128-084838.sql.gz--max-allowed-packet=512M -h 
mariadb -P 3306 -uroot --events --single-transaction --routines redacted
+ sudo -Eu dbbackup tee /tmp/backups/mysql_redacted_mariadb_20231128-084838.sql.gz
mysqldump: Couldn't execute 'select column_name, extra, generation_expression, data_type from information_schema.columns where table_schema=database() and table_name='address' order by ordinal_position': Unknown column 'generation_expression' in 'field list' (1054)
+ exit_code=0
```

### Environment

- Image version / tag:  v4.0.22
- Host OS: CentOS 7
- MariaDB server version: 10.1

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

    
### Possible fixes
Probably incompatibility in the version of mysqldump libraries with the version of our MariaDB server? Up to now we have been using your old dedicated container image for MySQL backup (not available anymore) which worked well for years... Kudos for that.

**Comment by tiredofit** [comment]
Interesting one. We're using the latest MariaDB client - More than likely they've started deprecating some old functions as MariaDB 10.1 is quite old and out of support for a couple of years now (2020). If you can get a working mysql dump from the command line within the image I can try to work that into the image, but I would advise moving up to something that is still supported by the MariaDB team. I am running at 10.6 and 10.11 on a couple hundred services with great success and there is apparent support for almost 4 more years..

**Comment by k3rn3l3rr0r** [comment]
Thanks for quick reply. I knew it exactly at the time of writing out the MariaDB version into the bug report description... I know it is way too OLD, but the instance serves quite a lot of services and the upgrade of the depending services has been dragging for a while now...  I will try to fix this on our side first. Closing this one for now.

**Comment by k3rn3l3rr0r** [comment]
Can confirm that everything is working fine with copy of the DB running on MariaDB 10.6 server...
