### ISSUE TITLE
Blobxfer not working with new 4.0 environment variables

### ISSUE THREAD

**Issue by RPYoshi** [tiredofit/docker-db-backup#297]
### Summary

Using the new environment variables the blobxfer process does not function correctly. No storage account or account key is found during the blobxfer call.

### Steps to reproduce

Replace the following variables keys with the new ones.
1. BLOBXFER_STORAGE_ACCOUNT -> DEFAULT_BLOBXFER_STORAGE_ACCOUNT
2. BLOBXFER_STORAGE_ACCOUNT_KEY -> DEFAULT_BLOBXFER_STORAGE_ACCOUNT_KEY

### What is the expected *correct* behavior?

Expected the blobxfer process should get the correct environment variable information and connect to azure storage account service.

### Relevant logs and/or screenshots

```
File "/usr/lib/python3.11/site-packages/blobxfer_cli/settings.py", line 331, in merge_global_settings
  raise ValueError('azure storage settings not specified')
ValueError: azure storage settings not specified
```

### Environment

- Image version / tag:  4.0.24/latest
- Host OS: Unraid

### Possible fixes
The blobxfer CLI function can take the storage account information from either a passed parameter or the environment variables BLOBXFER_STORAGE_ACCOUNT and BLOBXFER_STORAGE_ACCOUNT_KEY.

https://blobxfer.readthedocs.io/en/latest/10-cli-usage/

To fix add 
```
--storage-account ${backup_job_blobxfer_storage_account} --storage-account-key ${backup_job_blobxfer_storage_key}
```
to the following lines in:
https://github.com/tiredofit/docker-db-backup/blob/be619fb707c629231ea331500c4e06202d8ff851/install/assets/functions/10-db-backup#L1047
https://github.com/tiredofit/docker-db-backup/blob/be619fb707c629231ea331500c4e06202d8ff851/install/assets/functions/10-db-backup#L1602
https://github.com/tiredofit/docker-db-backup/blob/be619fb707c629231ea331500c4e06202d8ff851/install/assets/functions/10-db-backup#L1610

Additionally I think the **line 97** should be:
`BLOBXFER_STORAGE_ACCOUNT_KEY \`

and

**line at 191**:
```
transform_backup_instance_variable "${backup_instance_number}" BLOBXFER_STORAGE_ACCOUNT_KEY backup_job_blobxfer_storage_key
```

**Comment by tiredofit** [comment]
Thanks, will look into this. This makes sense, the application expects specific environment variables.

**Comment by tiredofit** [comment]
`4.0.2.5` will contain these fixes that should restore Azure/Blobxfer functionality!

https://github.com/tiredofit/docker-db-backup/commit/f031d787aeb31500d543b5942bfe64f601998f01

**Comment by RPYoshi** [comment]
Wow you are very fast! Thank you!

**Comment by RPYoshi** [comment]
Is the line 97 change relevant as well?

**Comment by tiredofit** [comment]
Yes, sorry that's hiding in commit https://github.com/tiredofit/docker-db-backup/commit/3eed5fc8a0001c385cc9ab01759940487f8c092e
