### ISSUE TITLE
Update AWS CLi to remove deprecation warning in STDERR in v3.x

### ISSUE THREAD

**Issue by alwynpan** [tiredofit/docker-db-backup#298]
### Summary

For v3.x, AWS CLi version 1.25.97 is installed. Lately, it started to throw a deprecation warning in STDERR due to [Use of pkg_resources is deprecated in favor of importlib.resources, importlib.metadata and their backports (importlib_resources, importlib_metadata).](https://setuptools.pypa.io/en/latest/pkg_resources.html)

It is not a big deal for many, but it breaks our post-backup script that detects the exit code and STDERR and logs an incident if an error is detected.

I understand we are moving to v4.x. However, v4.x was not thoroughly tested and approved to be used in our organization. I hope we can still patch the v3.x for the time being.

### Steps to reproduce

Run a backup with v3.12.0.

### Relevant logs and/or screenshots

```bash
[INFO] ** [db-backup] Cleaning up old backups on S3 storage
/usr/bin/aws:4: DeprecationWarning: pkg_resources is deprecated as an API. See
https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('awscli==1.25.97', 'aws')
```

### Environment

- Image version / tag:  3.12.0
- Host OS: Ubuntu Jammy

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

    
### Possible fixes

I have fixed it on [my branch](https://github.com/alwynpan/docker-db-backup/tree/feature/update-aws-cli). I am not sure if @tiredofit wants to create a release branch to merge this update in.

**Comment by tiredofit** [comment]
OK! Thanks for catching this. I'll take these changes and move into 4 after I deal with a timer bug that I need to resolve before anything else.

In the meantime `3-3.12.2` should be built in the next hour and available.

AWS CLI v2 I am more than happy to take some PRs on it. I dont have a usecase for it personally so it doesn't get much development effort.. Am ok with moving it to V2..
