### ISSUE TITLE
Timezone-setting missing

### ISSUE THREAD

**Issue by bd8392** [tiredofit/docker-db-backup#30]
Hi =) I've discovered that the container is not able to set a Timezone...So you can't plan Backups properly...a TZ-variable would be really nice (as this would also work in swarm) =)

**Comment by tiredofit** [comment]
Have a look at the base image `https://github.com/tiredofit/docker-alpine/blob/3.11/README.md` environment variables for information on setting timezone.

**Comment by bd8392** [comment]
Oh cool :-) that's perfect thank you very much :-))) sorry I've overlooked that...
