### ISSUE TITLE
New env var for SPLIT_DB?

### ISSUE THREAD

**Issue by Tyree** [tiredofit/docker-db-backup#300]
Is there a new var for SPLIT_DB? I have all other vars updated for 4.3, but I don't see an equivalent for that.
Thanks!

**Comment by Tyree** [comment]
Nevermind, I guess. I changed the SPLIT_DB key to DB01_SPLIT_DB and then it worked. Still, I don't see any mention of that key in the docs. But the deprecation warning went away and I still get split backups.

**Comment by tiredofit** [comment]
That's an omission on my end. I will patch up the README and make sure it exists in the DB sections.

**Comment by Tyree** [comment]
Great! Thanks!

**Comment by tiredofit** [comment]
In place - https://github.com/tiredofit/docker-db-backup/commit/b705982ae1ae94636023a182c848fa726bd7b8f0
