### ISSUE TITLE
`mysqldump: unknown option` when having multiple value options in `DEFAULT_EXTRA_OPTS`

### ISSUE THREAD

**Issue by ToshY** [tiredofit/docker-db-backup#310]
### Summary

Upgrading from `3.x` (`3.4.1`) to `4.x` (`4.0.32`) gives mysqldump `unknown option` result when having multiple/space delimited values in `DEFAULT_EXTRA_OPTS`:

`.env`
```.env
DEFAULT_EXTRA_OPTS="--hex-blob --no-tablespaces"
```

`docker compose logs -ft db-backup`
```console
mysql-backup-1  | 2023-12-17T17:51:28.207617591Z mysqldump: unknown option '--no-tablespaces''
```

When only using a single value, e.g. `DEFAULT_EXTRA_OPTS="--no-tablespaces"`, there are no issues.

### Steps to reproduce

A basic MySQL + db-backup (example) setup with environment variable `DEFAULT_EXTRA_OPTS` set in `.env`, e.g.  `DEFAULT_EXTRA_OPTS="--hex-blob --no-tablespaces"` .

### What is the expected *correct* behavior?

No issue when dumping database when having multiple extra options.

### Relevant logs and/or screenshots

`docker compose logs -ft db-backup`
```console
mysql-backup-1  | 2023-12-17T17:50:26.758349361Z + transform_backup_instance_variable 01 EXTRA_OPTS backup_job_extra_opts
mysql-backup-1  | 2023-12-17T17:50:26.758680902Z + grep -q '^DB01_EXTRA_OPTS=' /tmp/tmp.hPixKnHptg
mysql-backup-1  | 2023-12-17T17:50:26.759329919Z + grep -q '^DB_EXTRA_OPTS=' /tmp/tmp.hPixKnHptg
mysql-backup-1  | 2023-12-17T17:50:26.759982072Z + grep -q '^EXTRA_OPTS=' /tmp/tmp.hPixKnHptg
mysql-backup-1  | 2023-12-17T17:50:26.760737979Z + grep -q '^DEFAULT_EXTRA_OPTS=' /tmp/tmp.hPixKnHptg
mysql-backup-1  | 2023-12-17T17:50:26.761839394Z ++ grep '^DEFAULT_EXTRA_OPTS=' /tmp/tmp.hPixKnHptg
mysql-backup-1  | 2023-12-17T17:50:26.762558332Z ++ cut -d = -f2
mysql-backup-1  | 2023-12-17T17:50:26.763487965Z + '[' ''\''--hex-blob --no-tablespaces'\''' '!=' unset ']'
mysql-backup-1  | 2023-12-17T17:50:26.764044248Z ++ grep '^DEFAULT_EXTRA_OPTS=' /tmp/tmp.hPixKnHptg
mysql-backup-1  | 2023-12-17T17:50:26.764147622Z ++ cut -d = -f2-
mysql-backup-1  | 2023-12-17T17:50:26.765352701Z + export 'backup_job_extra_opts='\''--hex-blob --no-tablespaces'\'''
mysql-backup-1  | 2023-12-17T17:50:26.765361648Z + backup_job_extra_opts=''\''--hex-blob --no-tablespaces'\'''
...
mysql-backup-1  | 2023-12-17T17:51:28.204655645Z + run_as_user mysqldump --max-allowed-packet=512M -h mysql -P 3306 -u<omitted> --events --single-transaction --routines ''\''--hex-blob' '--no-tablespaces'\''' <omitted>
mysql-backup-1  | 2023-12-17T17:51:28.204711189Z + pigz -q -3 -p 4 --rsyncable
mysql-backup-1  | 2023-12-17T17:51:28.204769398Z + sudo -Eu dbbackup mysqldump --max-allowed-packet=512M -h mysql -P 3306 -u<omitted> --events --single-transaction --routines ''\''--hex-blob' '--no-tablespaces'\''' <omitted>
mysql-backup-1  | 2023-12-17T17:51:28.204928530Z + run_as_user tee /tmp/backups/01_dbbackup.b1TpZo/mysql_<omitted>_mysql_20231217-185128.sql.gz
mysql-backup-1  | 2023-12-17T17:51:28.205157075Z + sudo -Eu dbbackup tee /tmp/backups/01_dbbackup.b1TpZo/mysql_<omitted>_mysql_20231217-185128.sql.gz
mysql-backup-1  | 2023-12-17T17:51:28.207617591Z mysqldump: unknown option '--no-tablespaces''
```

### Environment

- Image version / tag:  `4.0.32`
- Host OS: `Ubuntu 22.04.2 LTS`

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>
    
### Possible fixes

Don't really know the root cause, only think that `''\''--hex-blob' '--no-tablespaces'\'''` looks kind of strange, which possibly causes issues for mysqldump 🤷‍♂️

**Comment by tiredofit** [comment]
`4.0.33` will resolve this, we're getting unintended quotes added in while I process the multiple environment variables to split up into their own jobs in some of them. I just tested with my own string of "BACKUP01_EXTRA_BACKUP_OPTS=--extra1 --extra2 --exta3" with success.

**Comment by ToshY** [comment]
Hey @tiredofit 👋 

Tested `4.0.33` with `DEFAULT_EXTRA_OPTS="--hex-blob --no-tablespaces"` and it works again. 

Thanks for the quick fix. Much appreciated 🥇
