### ISSUE TITLE
DB-CLEANUP doesn't work when using root

### ISSUE THREAD

**Issue by bd8392** [tiredofit/docker-db-backup#32]
This code-section is wrong:
```
### Automatic Cleanup
    if [[ -n "$DB_CLEANUP_TIME" ]]; then
          find $DB_DUMP_TARGET/  -mmin +$DB_CLEANUP_TIME -iname "$DBTYPE_$DBNAME_*.*" -exec rm {} \;
    fi
```
If you use root, no DB-NAME is specified, which results into no cleanup...just remove name-section and delete everything in the bakup-folder older than given time like this:
```
### Automatic Cleanup
    if [[ -n "$DB_CLEANUP_TIME" ]]; then
          find $DB_DUMP_TARGET/  -mmin +$DB_CLEANUP_TIME -exec rm {} \;
    fi
```
It's the easiest solution that comes to my mind...hope it works...

**Comment by tiredofit** [comment]
Nice find! That's been sitting there for 3 years unnoticed. I agree and will make that adjustment now.

**Comment by tiredofit** [comment]
Tagged as `tiredofit/db-backup:1.20.1` / `latest`

**Comment by bd8392** [comment]
Very cool! Thanks :-)
