### ISSUE TITLE
Missing backup-now

### ISSUE THREAD

**Issue by Mark24Slides** [tiredofit/docker-db-backup#323]
### Summary
Missing manual backup command.
`backup-now` command is not found (MODE=manual).

### Steps to reproduce

Run `backup-now` command, with MODE=manual.
Catch "command not found" error.

### What is the expected *correct* behavior?

Manual backup run, as it was on 3.12.2 (decided to migrate from this version to the latest v4).

### Relevant logs and/or screenshots

backup-now is missing in backup-now.

Also, checked services, no 10-db-backup folder there:
![image](https://github.com/tiredofit/docker-db-backup/assets/136308358/401190b3-f5b7-4f2a-b8f8-e472bd5709e4)

### Environment

- Image version / tag: 4.0.34
- Host: Kubernetes, v.1.26

**Comment by tiredofit** [comment]
The `backup(xx)_now` scripts are automatically generated in > 4.x - Looks like there are missing environment variables - For the most part upgrades should just "work" but in cases where there has been lots of work arounds best to review and get it up to the newer format of `DB(XX)_varname`

**Comment by falkheiland** [comment]
in my case, i used PASS_FILE with 3.x - this is gone now, not using docker secrets right now
