### ISSUE TITLE
Allow specifying extra options for the various backup commands

### ISSUE THREAD

**Issue by skylord123** [tiredofit/docker-db-backup#33]
So I need to add the option `--default-character-set=utf8mb4` to the `mysqldump` command but others will not want this option. It would be awesome if I could specify custom options for the backup commands.

The reason I need this is described in the Nextcloud docs (backups wont work for utf8mb4 unless specified on the dump command):
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html#mariadb-support

Thanks!

**Comment by tiredofit** [comment]
Interesting - I haven't seen those types of issues when restoring to Nextcloud. Am a very heavy user- but I agree, some additional arguments would be useful. Give me a few days to finish off an update to all of the images and I can easily integrate this.
