### ISSUE TITLE
Unable to run backup

### ISSUE THREAD

**Issue by tommy-b-10** [tiredofit/docker-db-backup#34]
Using unRaid Docker container (Both the CA app store one, as well as creating a custom one with the latest release from the docker hub), I get the following error when attempting to run 'backup-now':

`/usr/local/bin/backup-now: line 4: /etc/s6/services/10-db-backup/run: No such file or directory`

Is this a configuration error on my part? I am attempting to backup a mongo database from an external host.

**Comment by joergmschulz** [comment]
Thanks a lot!
```
/assets/functions/00-container: line 357: /tmp/state/$(basename "$PWD"): Is a directory
[INFO] ** [mariadb-backup] Backup Functionality initialized at Thu Sep 17 16:14:54 CEST 2020
[INFO] ** [mariadb-backup] Dumping database: wordpress at Thu Sep 17 16:14:55 CEST 2020
```
this translates to: the backup-now script works, but throws a warning
