### ISSUE TITLE
neither DB_USER nor DB_USER_FILE are set but are required

### ISSUE THREAD

**Issue by tadeo-n** [tiredofit/docker-db-backup#35]
On version 1.21.3 I got this error when I run backup of MongoDB instance without authentication.

bash-5.0# backup-now
** Performing Manual Backup
[ERROR] ** [db-backup] error: neither DB_USER nor DB_USER_FILE are set but are required

**Comment by tiredofit** [comment]
Have a peek at `tiredofit/db-backup:1.22.0` - The fix should be included.

**Comment by tadeo-n** [comment]
same problem occurs on 1.22.0

**Comment by tiredofit** [comment]
OK - lets try a different avenue. Set this environment variable: `CONTAINER_ENABLE_DOCKER_SECRETS=FALSE`

**Comment by tadeo-n** [comment]
With `CONTAINER_ENABLE_DOCKER_SECRETS=FALSE` works!
