### ISSUE TITLE
option to ignore system databases : information_schema, performance_schema, mysql

### ISSUE THREAD

**Issue by extremeshok** [tiredofit/docker-db-backup#37]
Please can you add the option to ignore system databases, ie: 
 information_schema, performance_schema, mysql

**Comment by alwynpan** [comment]
Not exactly what you want, but maybe try with `--no-tablespaces` option in `EXTAR_OPTS`?

**Comment by tiredofit** [comment]
Much more capabilities are in version 3.xx for backing up ALL, or Multiple databases that should eliminate those system databases being backed up..
