### ISSUE TITLE
s6-maximumtime: warning: child process crashed

### ISSUE THREAD

**Issue by tijnhendrikson** [tiredofit/docker-db-backup#38]
It seems, if the database is bigger and consumes more time, it crashes due to the s6 maximumtime limit.

When I manually run backup-now everything is fine.
But the automatic crons wont work. In my logs I find something like:

```
[INFO] ** [db-backup] Backup routines Initialized on Thu Aug 27 03:09:30 CEST 2020
[NOTICE] ** [db-backup] Compressing backup with gzip
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 10-db-backup: executing...
s6-maximumtime: warning: child process crashed
[cont-finish.d] 10-db-backup: exited 111.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

I was reading something about this on https://github.com/just-containers/s6-overlay:
`S6_KILL_FINISH_MAXTIME (default = 5000): The maximum time (in milliseconds) a script in /etc/cont-finish.d could take before sending a KILL signal to it. Take into account that this parameter will be used per each script execution, it's not a max time for the whole set of scripts.`

Not sure if it's related. But anyways, it shouldn't right?

**Comment by tiredofit** [comment]
Not related unfortunately - that's more used for when you are taking a container down and you want to shut the process down gracefully.

I am interested in a bit in finding out on what size of database / type you are trying to backup. The largest one I back up regularly is approximately 980gb.

**Comment by tijnhendrikson** [comment]
Thanks for your quick reply:) Oh really, mine is very small in comparison, maybe 1G. When running manually it takes maybe 2 minutes not much more :'). Maybe it somehow hangs elsewhere. I didn't see it happening real-time. I can test a bit further by actually monitoring the cronjob triggering, I'll let you know when I have more input!

**Comment by tiredofit** [comment]
Latest releases I have moved away from using cron and wrote my own scheduler inside the tool itself - What you can do is try either the following: `CONTAINER_LOG_LEVEL=DEBUG` as an environment variable, or a last resort `DEBUG_MODE=TRUE` which will give you far too much output and leak all your credentials at the same time to your console which should give you an idea of whats happening. Keep me posted. I can add more debug routines if necessary.

**Comment by tijnhendrikson** [comment]
Thanks for your help! I'm not really sure why, but it seems that the issue was 'magically' solved. When changing settings and rebooting the container, the cronjobs now run fine. If I find any other issues or get any idea of cause of it was I'll let you know 👍
