### ISSUE TITLE
Way to Nofiy on Backup Failure?

### ISSUE THREAD

**Issue by zicklag** [tiredofit/docker-db-backup#39]
Hey there, I'm looking to use this container, but I would like a way to run a simple curl command to notify my webhook when a backup fails. Is there a way to detect a backup failure in the post-script?

**Edit:** I see that you have SMTP setup in the base image. Is there a way to just have it send an Email when the backup fails? That would also work, while the webhook would still be preferable.

**Comment by tiredofit** [comment]
You could do whatever you needed to with the post script - however it's a bit challenging to fully determine is the backup fails. Since these are all processes - we could likely rely on the exit code when performing the backup to tell if it has passed or failed, but that really doesn't give us the detail, and I am assuming there is going to be a lot of false positives.

How I do it with my own monitoring system (Zabbix Template is included in this source repo) is that I get notified if I don't hear anything from the container in 24 hours as one sign of trouble. Another way I go about it is I get an alert if the backup is 20% different in size than the previous days backup. That could be easily written in bash or python as well to be able to send the payload to whatever monitoring system. I'd just use the same folder where the backups are stored and store the last good file name / file size in a file like .filesize, and perform comparisons of it that way.

I can put some modifications into the image to trap the exit code and put it as a variable, again, I don't hold too much hope on that one, but it should be easy enough to do. I'll get to that in a few days.

**Comment by zicklag** [comment]
That would be great. Yes, exit code may not be the best metric, but I haven't gotten hardly any false positives using that strategy for my own backup containers so I think it's good enough for me for now. I'll also take a look at Zabbix sometime.

**Comment by zicklag** [comment]
Oh, also, what do you think about an environment variable that could be used to inline a post-run script? My notification script is a one-liner curl command and it's very convenient not to have to create a volume just for the script when it is trivial to inline it in a YAML with the wrapping line syntax.
```yaml
POST_SCRIPT: >
  curl -X POST -qd text="Database backup of some database failed" -d icon_emoji=":no_entry:"
  https://some.rocket.chat/hooks/akfja;skfdalsjdflkajsdfkjdd
```

**Comment by tiredofit** [comment]
Exit codes now available inside the script as `${exit_code}`. It's also `${1}` if using the custom post scripts.

`POST_SCRIPT` environment variable available does just what you have proposed, you'll need to take advantage of some of the environment variables yourself to build your command.

These are what I use for the post script example:
`"${exit_code}" "${dbtype}" "${dbhost}" "${dbname}" "${now_date}" "${now_time}" "${target}" "${FILESIZE}" "${MD5VALUE}"`

**Comment by zicklag** [comment]
That's perfect, thanks! :smiley:

**Comment by zicklag** [comment]
@tiredofit when trying to use the `POST_SCRIPT` environment variable I get an error:

    curl -X POST -qd text="Database complete" https://examplechat.com/hooks/blablaba/blablalba,
    : No such file or directory,

My guess is that the quotes shouldn't be around this variable here and that it is making it treat the entire variable as a program path and not an inline bash line:

```bash
    if [ -n "$POST_SCRIPT" ] ; then
        print_notice "Found POST_SCRIPT environment variable. Executing"
        "${POST_SCRIPT}"
    fi
```

I can't build the container right this second myself so I haven't tested it yet, though.

**Comment by tiredofit** [comment]
Try running it with DEBUG_MODE=TRUE which should give an understanding of where it's failing.

I can also throw a script inside db-backup fro Rocketchat/Mattermost/Slack style notifications.

I use this variant all over the place in my own infrastructure

````bash
#!/bin/bash

url="${WEBHOOK_URL}"
username="${FROM}

to="$1"
subject="$2"

emoji=':first_place:'

message="${subject}:\nContainer: $3 on $4\nStatus: $5\n:Message $6\nAdditional: $7"

payload="payload={\"channel\": \"${to//\"/\\\"}\", \"username\": \"${username//\"/\\\"}\", \"text\": \"${message//\"/\\\"}\", \"icon_emoji\": \"${emoji}\"}"
/usr/bin/curl -m 5 --data-urlencode "${payload}" $url
````

You get the idea..

**Comment by zicklag** [comment]
I figure it out. Just needed to add `eval`. Here's a PR: https://github.com/tiredofit/docker-db-backup/pull/41.

> I can also throw a script inside db-backup for Rocketchat/Mattermost/Slack style notifications.

I don't we need to. I think the post script options with the environment variable and the mount should be good enough now. Though it might not hurt to add that script example in the README and maybe show how to pass that in a `docker-compose.yml` in the `POST_SCRIPT` because people might not know about the multi-line YAML string syntax.

**Comment by mitohund** [comment]
I would like to piggyback on this (three years later) and please forgive me if I'm being slow here, but I'm a self-taught self-hoster.

I've configured msmtp correctly (I can send an email from command line inside the container), but I don't get any emails after a database dump. What am I missing? Probably something like the scripts you two have been putting together above?

I would prefer to only get emails if the backup failed (according to the exit code would be fine for starters). But I would already be happy if I got any email at all. ;-D

Would you be able to help me out? Any input would be highly appreciated.

**Comment by zicklag** [comment]
Hey there!

I've set my `POST_SCRIPT` environment variable to:

```
test "0" = "$exit_code" || echo "replace me with your email send command"
```

Note, that you may need to replace `$exit_code` with `$$exit_code` to escape the `$` sign if you are using it in a `docker-compose.yml` file.

I haven't updated the container in a while, I'm using `tiredofit/db-backup:2.1.1` to be exact.

I hope that helps!

**Comment by mitohund** [comment]
Wow thanks for the lightning quick response after such a long time!

Even better, this looks like I even mostly understand what it does. I'll be able to test later today or tomorrow, but two quick questions already:

1. What does "test" do at the beginning?
2. Exit code 0 is success, right? So if I want to be notified upon failure, I would need to use a different one? How do I know which exit codes exist? And which ones make sense? Or just "if it's not 0" - and how would I do that?

**Comment by zicklag** [comment]
No problem!

The `test` command will exit `0` if the condition, `"0" = "$exit_code"`, is `true`, and it will exit non-zero if the check is `false`.

The `||` is bash syntax that says:

> run the command after the `||` if the command before it exits non-zero.

So putting that together we're saying:

> If the exit code is not zero, then run `echo "replace me..."`

So this will run our `echo` command only when the backup fails, which is already what you want.

In this case you don't really need to know what exit codes exist. Anything that isn't 0 means an error, so you want to send a notification for anything that isn't 0.

---

Also, just to be clear, you want to replace the whole `echo` command after the `||` with your email send command, not just the section in quotes.

Good luck with your self-hosting efforts!

**Comment by mitohund** [comment]
Fantastic, thanks so much! And I've learnt a few more things beyond the problem at hand!

This looks I should get it to work. Will confirm when I get to trying it out. But one more off-topic question: why are you on such an old version of the container? Do you prefer not to update your containers?

**Comment by zicklag** [comment]
No, this is just a server that I leave running and don't have to baby-sit that much. I update my containers when I have time to, I just hadn't needed to mess with this one in a while.

**Comment by mitohund** [comment]
Ah, also, I ran into the same issue as #117 and #126 and had to add `POST_SCRIPT_SKIP_X_VERIFY: TRUE`. @tiredofit is it possible that the problem behind these issues still exists?

This actually also cost me a lot of time - it took me a while to realise I could check GitHub for "not executable" issues - did I mention I'm an amateur? :D

**Comment by zicklag** [comment]
> can I cause an error some other way?

I'm not sure, I don't know of any other way to cause an error. 🤔

If you wanted you could change `test "0" = "$$exit_code"` to `test "0" = "1"`, which will always be false, so that it will act like the backup failed every time, even if it succeeds.

That should let you test whether or not it will send the email.

> would it not make sense to add a maximum retrying time and throw an error afterwards?

That might make sense, but if your database isn't running at all, the data can't change, so taking a backup might not make sense.

Maybe something separate to health-check the database makes more sense for that use-case. I think that's pretty much based on preference.

---

I'm not sure why you had to add an `&` at the end. That's strange to me. I don't _think_ it hurts, as long as you're actually getting emails.

The reason you had to use one `|` instead of two for the second command, is because two pipes means "or run this command if the previous fails", and one pipe means "take the stardard output of the first command and pipe it to the stardard input of the second command".

So in this case you want to take your `echo "Subject: Alarm!"` command, and take it's output, which is `Subject: Alarm!` and send it to the input of the `msmtp` command, so that `msmtp` knows what to put in the Email.

---

And it's OK that you're new to it! I've learned most of what I know just by doing things I needed/wanted to do, even if I didn't know how yet.

Learning by doing really does work, if you put the time and effort into it.

**Comment by mitohund** [comment]
> The reason why you need the skip executable check is because you aren't actually running a script, yet a series of commands instead that would normally go inside a script. While it works, you get weird results as you are getting with MSMTP.

Thanks for clarifying @tiredofit. Since it worked, I was about to leave it that way. But I was getting another error message referencing line 789 in assets/functions/10-db-backup. So I decided to put my commands in a script hoping to clear that up. But I am still getting the same error that it's not executable, even though it is set to executable for all. The funny thing is that it executes just fine anyway. So I guess I'll set the skip verify variable again to get rid of that error message?

Also, what's the correct way to invoke my script? "POST_SCRIPT: '/assets/scripts/post/my_script.sh'"? Is it possible that it doesn't matter what I put in here, since any .sh file found in that folder will be executed?

Last question: if a database is not reachable, this container keeps trying until it is. Would it not make sense to limit the retries and throw an error after some time?

And @zicklag thanks for the support throughout and the encouraging words!

**Comment by mitohund** [comment]
Ah, so if I'm using a script, I should actually leave out the POST_SCRIPT variable! Is that correct? From what I see, the script is then executed, the (regular) logs show it as executed, and no error messages. 

The POST_SCRIPT variable is not actually for a script, but for a command? But then requires the "POST_SCRIPT_SKIP_X_VERIFY: TRUE" variable to not throw an error?

I'm sorry, I'm just really confused now.

**Comment by tiredofit** [comment]
`POST_SCRIPT` syntax is correct eg `POST_SCRIPT=/tmp/script.sh`

What you are bumping up against is the other one which executes any script in that directory:

I have a check to see if `SCRIPT_LOCATION_POST` exists and if there are files in it, and if so, execute any file with the extension of .sh. 

`POST_SCRIPT_SKIP_X_VERIFY` works the same for both of those different types (lines 787-822) in `/assets/functions/10-db-backup`

**Comment by tiredofit** [comment]
Re Database timeout. I'll consider it. It's something that's been in the code since the beginning and if I can get supporters to bring this to version 4 I'll introduce some sort of time out along with being able to notify when that certain (and other) exceptions occur. 

You can also just skip it entirely right now with `SKIP_AVAILABILITY_CHECK=TRUE`

**Comment by mitohund** [comment]
OK cool, thanks for explaining. I had put my script in `/assets/scripts/post/`, but then it was triggered twice - once by the environment variable and once by the automatic check, I guess.

I'll now put it in the folder, leave out `POST_SCRIPT` and rely on the automatic check. Cool!

**Comment by mitohund** [comment]
> You can also just skip it entirely right now with `SKIP_AVAILABILITY_CHECK=TRUE`

I tried this, but the exit code remains 0, from what I can tell. So unfortunately it doesn't help me.

I'll integrate this into my backup system now and observe for a while. I try to always donate a little money to open source projects I use. So I'll do the same here. But me alone probably won't make a big dent in funding the time you're spending on this. But aside from the money, thanks for all the work you put into this!
