### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by PierrePDP** [tiredofit/docker-db-backup#40]
Good day

I would just like to find out if support for Azure is on the horizon?

Cheers

**Comment by tiredofit** [comment]
Do you mean Azure Databases or Azure File Storage for the backups? I'm not familiar in the slightest with Azure, never have used, but an open to investigating. A while back someone had requested Microsoft SQL server support which we could not do, things may have changed with availability of command line tools.

**Comment by PierrePDP** [comment]
Apologies, I should've been more clear in my question. I was referring to Azure File Storage for the backups.

**Comment by tiredofit** [comment]
This tool https://github.com/Azure/blobxfer looks promising to be able to upload and download to Azure, also being able to synchronize the entire directory - which could help with retention, something I am not doing with the S3 support (you have to manually delete your backups).

Are you able to spend some time getting me some working command line functions with this tool to be able to upload a file? Then I can easily integrate this.

**Comment by eoehen** [comment]
@tiredofit  FYI
Add support for `mssql` backup and azure storage upload with [blobxfer](https://github.com/Azure/blobxfer).
Issue: #163  Pullrequest: #165 
Issue: #164  Pullrequest: #166

**Comment by eoehen** [comment]
@tiredofit can we close this issue?

**Comment by tiredofit** [comment]
I think we can, thanks again for your contribution.
