### ISSUE TITLE
`DB_USER` and `DB_PASS` became required for all database types

### ISSUE THREAD

**Issue by alwynpan** [tiredofit/docker-db-backup#42]
`DB_USER` and `DB_PASS` were optional for mongodb, and `DB_PASS` was optional for many other database types. However, due to recent changes, they now became required for all database types. Failed to supply either one will fail the backup. See error:

`[ERROR] ** [db-backup] error: neither DB_USER nor DB_USER_FILE are set but are required`
`[ERROR] ** [db-backup] error: neither DB_PASS nor DB_PASS_FILE are set but are required`

This can be fixed either from the upstream or in this repo. I will work on a temp fix.

**Comment by tiredofit** [comment]
I'll take a look at your fix, but in the Readme it states:

`If you are trying to backup a database that doesn't have a user or a password (you should!) make sure you set CONTAINER_ENABLE_DOCKER_SECRETS=FALSE`

This is a byproduct of us checking for Docker Secrets. Let me know if it works for you?

**Comment by tiredofit** [comment]
I like it! I will merge the PR as this fixes having to set the container docker secrets flag. Thank you for this.

**Comment by tiredofit** [comment]
Tagged as `tiredofit/db-backup:2.2.0`

**Comment by alwynpan** [comment]
@tiredofit Thanks for the prompt response. 👍 

Sorry, I should have checked the updated README. I have been using this image for long and didn't notice the changes made in the README file.
