### ISSUE TITLE
backup-now throws`date: invalid date '@'` warning

### ISSUE THREAD

**Issue by alwynpan** [tiredofit/docker-db-backup#44]
`backup-now` throws this message:

[NOTICE] ** [db-backup] Next Backup at 
date: invalid date '@'

It can be removed by adding a condition, will push a fix soon.

**Comment by tiredofit** [comment]
We noticed this on my inclusion of some of this script on my `tiredofit/mariadb` image today. Your fix is much more elegant than my sleepy eyed/no coffee hack that I introduced. Thanks for this!

**Comment by alwynpan** [comment]
Thank you for making such a good tool, I love it!

**Comment by tiredofit** [comment]
Tagged as `tiredofit/db-backup:2.2.1`
