### ISSUE TITLE
[Bug] Docker secrets not working as of v2.1.1

### ISSUE THREAD

**Issue by tpansino** [tiredofit/docker-db-backup#46]
I inject my DB password via Docker Secrets, and noticed that this is no longer working as of v2.1.1.

Looking at the code, the root cause appears to be a result of #43 . Specifically, these lines:
```
[[ ( -n "${DB_PASS}" ) ]] && file_env 'DB_PASS'
```
Which are neglecting to check whether `DB_PASS_FILE` is also set, in which case the password still needs to be read and injected.

I'll open a PR for this shortly.

---

This was a surprising regression, and I only caught it because I have monitoring which indicates my backups haven't succeeded for X amount of time. @tiredofit , just curious if you've thought about any plans for a test suite? Or a checklist for the manual testing that should go into each release?

In any case, thanks for the tool 👍

**Comment by tiredofit** [comment]
I have to apologize that this crept in. I am not using secrets personally in my environment and this was a PR that I approved to allow blank DB users/passwords in the past week. I would appreciate a PR to get secrets up and running, and I'm also interested in hearing more about any test suites you could point me to?

**Comment by tpansino** [comment]
Thanks for the quick response!

> I have to apologize that this crept in.
No worries, bugs happen. I'm just happy that you set the project up well and open-sourced it so a random person like me can fix it.

A test suite people can also contribute to would definitely help with future regressions though. The main testing framework I know of for Bash scripts is called [BATS](https://github.com/sstephenson/bats). It's output is TAP compliant, so you can do fun Perl-ish things with it if you're into that sort of thing.

Also, British Columbia? Portland Oregon here, hope the smoke we've been sending up your way is clearing up 👋

**Comment by tiredofit** [comment]
Merged. I'll tag it with a release in the AM when I am more on it - Thank you for this. 
As you can imagine, I built this with one purpose in mind and then expanded on it when I put it out to the public, so I do miss a few things embarrassingly on this and some of the other images I have posted publicly - So I appreciate the quick fix and help on getting things back on track!

I've read about BATS, but will take a closer eye. Automated testing in a CI pipeline seems to be the final frontier for me, and I'm eager and interested in evaluating this more. We have similar stages in our pipelines working in my own environment, I'm a few days away from being able to figure out the docker hub hooks that I can take advantage of and feel this would be very useful to not be able to push a :latest or even a tag that doesn't pass specific checks. Am also very interested in bending it to be able to push multiarch images.

*cough* the smoke - I can't say it's entirely your area, we've had our own fair share of fires in the past week and a half, but is certainly has been apocalyptic. I'm no longer on the mainland of BC, but now in a small valley in nook of Vancouver Island. It was gross for the past 8 to 9 days bringing on some real "fight or flight" symptoms. The skies broke this morning and I saw blue so I do hope that with temps dropping you may be seeing something similar soon!
