### ISSUE TITLE
Cannot backup PostgreSQL 13

### ISSUE THREAD

**Issue by CorneliousJD** [tiredofit/docker-db-backup#48]
[INFO] ** [db-backup] Dumping database: postgres
[NOTICE] ** [db-backup] Compressing backup with gzip
pg_dump: error: server version: 13.0 (Debian 13.0-1.pgdg100+1); pg_dump version: 12.4
pg_dump: error: aborting because of server version mismatch
[NOTICE] ** [db-backup] Generating MD5 for pgsql_postgres_10.0.0.10_20201008-113031.sql.gz
[NOTICE] ** [db-backup] Backup of pgsql_postgres_10.0.0.10_20201008-113031.sql.gz created with the size of 20 bytes

**Comment by tiredofit** [comment]
Thanks. I'm afraid we're going to have to wait until Alpine edge gets the client in their repositories. Currently it's at 12.4. I will monitor and if I see no movement will build the clients manually which has the side effect of making the image much larger.

**Comment by CorneliousJD** [comment]
> Thanks. I'm afraid we're going to have to wait until Alpine edge gets the client in their repositories. Currently it's at 12.4. I will monitor and if I see no movement will build the clients manually which has the side effect of making the image much larger.

Understood, I will use another backup method in the interim for now, it's just manual.

Looking forward to db-backup supporting pgsql 13 so I can keep utilizing this, it's been awesome so far :) 

Thanks for the update!

**Comment by tiredofit** [comment]
Hi @CorneliousJD It's getting to that week time and I'm willing to try a localized build of psql 13 in the db-backup image. 
Would you be willing to test `tiredofit/db-backup:develop` for me? I'm just wanting to make sure my compiling is working as expected. If so, let me know the status and if successfull I'll push out a new `:latest: release.

**Comment by CorneliousJD** [comment]
@tiredofit sadly doesn't look like it's quite working - it says it's unable to connect.

Happy to test more if you re-build the develop branch. just let me know!

`/ # backup-now
** Performing Manual Backup
date: invalid date '@'
[NOTICE] ** [db-backup] Next Backup at 
Error loading shared library libpq.so.5: No such file or directory (needed by /usr/bin/pg_isready)
Error relocating /usr/bin/pg_isready: initPQExpBuffer: symbol not found
Error relocating /usr/bin/pg_isready: createPQExpBuffer: symbol not found
Error relocating /usr/bin/pg_isready: appendPQExpBufferChar: symbol not found
Error relocating /usr/bin/pg_isready: PQgetResult: symbol not found
Error relocating /usr/bin/pg_isready: PQstatus: symbol not found
Error relocating /usr/bin/pg_isready: appendPQExpBuffer: symbol not found
Error relocating /usr/bin/pg_isready: PQconndefaults: symbol not found
Error relocating /usr/bin/pg_isready: PQresultStatus: symbol not found
Error relocating /usr/bin/pg_isready: resetPQExpBuffer: symbol not found
Error relocating /usr/bin/pg_isready: PQgetCancel: symbol not found
Error relocating /usr/bin/pg_isready: PQntuples: symbol not found
Error relocating /usr/bin/pg_isready: PQresultErrorField: symbol not found
Error relocating /usr/bin/pg_isready: PQfreeCancel: symbol not found
Error relocating /usr/bin/pg_isready: PQexec: symbol not found
Error relocating /usr/bin/pg_isready: PQserverVersion: symbol not found
Error relocating /usr/bin/pg_isready: enlargePQExpBuffer: symbol not found
Error relocating /usr/bin/pg_isready: PQconninfoParse: symbol not found
Error relocating /usr/bin/pg_isready: PQdb: symbol not found
Error relocating /usr/bin/pg_isready: PQcancel: symbol not found
Error relocating /usr/bin/pg_isready: PQpingParams: symbol not found
Error relocating /usr/bin/pg_isready: PQtransactionStatus: symbol not found
Error relocating /usr/bin/pg_isready: destroyPQExpBuffer: symbol not found
Error relocating /usr/bin/pg_isready: PQfinish: symbol not found
Error relocating /usr/bin/pg_isready: PQerrorMessage: symbol not found
Error relocating /usr/bin/pg_isready: PQescapeStringConn: symbol not found
Error relocating /usr/bin/pg_isready: PQclientEncoding: symbol not found
Error relocating /usr/bin/pg_isready: PQconnectionNeedsPassword: symbol not found
Error relocating /usr/bin/pg_isready: PQmblen: symbol not found
Error relocating /usr/bin/pg_isready: termPQExpBuffer: symbol not found
Error relocating /usr/bin/pg_isready: PQgetvalue: symbol not found
Error relocating /usr/bin/pg_isready: appendPQExpBufferStr: symbol not found
Error relocating /usr/bin/pg_isready: PQclear: symbol not found
Error relocating /usr/bin/pg_isready: PQconnectdbParams: symbol not found
[WARN] ** [db-backup] Postgres Host '10.0.0.10' is not accessible, retrying.. (5 seconds so far)`

**Comment by tiredofit** [comment]
Thanks for this - looks like I missed out on some libraries.
There's a new version available for testing `tiredofit/db-backup:develop`

**Comment by CorneliousJD** [comment]
@tiredofit still getting this when executing. 

I know my connection info is correct because if I remove :develop it runs and I get the errors noted in the first part of this thread, and it generates backups that are empty, but it still connects. 

/ # backup-now
** Performing Manual Backup
date: invalid date '@'
[NOTICE] ** [db-backup] Next Backup at 
/etc/services.available/10-db-backup/run: line 272: pg_isready: command not found
[WARN] ** [db-backup] Postgres Host '10.0.0.10' is not accessible, retrying.. (5 seconds so far)
/etc/services.available/10-db-backup/run: line 272: pg_isready: command not found
[WARN] ** [db-backup] Postgres Host '10.0.0.10' is not accessible, retrying.. (10 seconds so far)
/etc/services.available/10-db-backup/run: line 272: pg_isready: command not found

**Comment by tiredofit** [comment]
OK, I see my problem now - Seems my development version is a bit too dev for anything but MSSQL right now. 

Let's hope that 3rd time is a charm on this new (1gb! image)

**Comment by CorneliousJD** [comment]
@tiredofit  yep looks good now! I see it dumping and actually creating a file now!

/ # backup-now
** Performing Manual Backup
[INFO] ** [db-backup] Dumping database: postgres
[NOTICE] ** [db-backup] Compressing backup with gzip
[NOTICE] ** [db-backup] Generating MD5 for pgsql_postgres_10.0.0.10_20201015-104006.sql.gz
[NOTICE] ** [db-backup] Backup of pgsql_postgres_10.0.0.10_20201015-104006.sql.gz created with the size of 316 bytes
[INFO] ** [db-backup] Dumping database: nextcloud
[NOTICE] ** [db-backup] Compressing backup with gzip
[NOTICE] ** [db-backup] Generating MD5 for pgsql_nextcloud_10.0.0.10_20201015-104006.sql.gz
[NOTICE] ** [db-backup] Backup of pgsql_nextcloud_10.0.0.10_20201015-104006.sql.gz created with the size of 19248557 bytes
[NOTICE] ** [db-backup] Sending Backup Statistics to Zabbix
[NOTICE] ** [db-backup] Cleaning up old backups
/ # ^C

**Comment by tiredofit** [comment]
Perfect! 
I managed to bring the image down to 559mb now so that's better.
I'll wrap this up and turn it into a release. Many thanks for testing.

**Comment by CorneliousJD** [comment]
No problem at all! I just re-ran develop again with the smaller image and it's still working, so it all looks good!

Should I continue to run :develop for now or swap back to :latest? Not sure how soon you plan to roll into main release.

thanks!

**Comment by tiredofit** [comment]
Tagged as `2.3.0` - Docker Hub is building. This also includes MSSQL support that I have been sitting on for a few months now.

**Comment by CorneliousJD** [comment]
I see the new build live, updated both my containers for db-backup (one for mysql, and the other for postgres) and both are working to backup good now, thank you for all of this!
