### ISSUE TITLE
If the value SPLIT_DB is set to TRUE post-script.sh only shows information about the last backed DB 

### ISSUE THREAD

**Issue by gruesomehit** [tiredofit/docker-db-backup#50]
I have differents DB in my mariaDB and I am interested to back it up in separate files not all inside the same file.

So, the script /assets/custom-scripts/post-script.sh is executed after the last DB backup and shows only stadistics about the last backed DB, not the previous ones. Can i have running this script with all  DB backed up ?

And by the way. Could you give an example to send this script trought the SMTP included in the container?

Thanks in advanced.

**Comment by tiredofit** [comment]
This has now been resolved integrated into `3.1.0` - The Post Script and Monitoring features fire per database backup as opposed to the entirety of the script.
