### ISSUE TITLE
InfluxDB - Backup of multiple databases fails

### ISSUE THREAD

**Issue by bambi73** [tiredofit/docker-db-backup#51]
Script contains `for` loop over `$DB_NAME` values likely to support backup of multiple InfluxDB databases but there is no setting for `target` in each iteration. So backup fails with `stat: can't stat '/tmp/backups/influx_home_assistant telegraf_192.168.1.199_20201110-233711.sql': No such file or directory`.

Adding `target=influx_${DB}_${dbhost}_${now}` solved problem for me.

**Comment by tiredofit** [comment]
Did you want to submit a PR on this and we can merge this in?

**Comment by bambi73** [comment]
Ok, will do that tomorrow.
