### ISSUE TITLE
wrong timezone

### ISSUE THREAD

**Issue by devmysoft** [tiredofit/docker-db-backup#59]
Hi, 
I have a question, the timezone is wrong even if I put the environment  TZ="Europe/Paris" and even if I add tzdata in the dockerfile... What can I do ? Thanks for your help !!

**Comment by jwillmer** [comment]
Since [this](https://github.com/tiredofit/docker-alpine/tree/master) is the base image I think you need to define it like this:

 `-e "TIMEZONE=Europe/Stockholm"`

But I agree that it should be added to the documentation. It is kind of important.

**Comment by devmysoft** [comment]
Sorry for my latest answer. I just tested and it's work with `TIMEZONE=Europe/Stockholm`. Thanks !
