### ISSUE TITLE
Make it possible to run the container with another user

### ISSUE THREAD

**Issue by Akruidenberg** [tiredofit/docker-db-backup#61]
I cant´ find any documentation how to run this container with another. I would like to run this container with the `--user` command. With security in mind, running as root is not a good idea.
When running with the `--user, i´ve got a lot of permission errors.

**Comment by tiredofit** [comment]
Upcoming version 4.x runs as root with S6-Overlay, unfortunately no way around not running it as root, but all commands execute as a regular user where the uid can be controlled for file access and saves.
