### ISSUE TITLE
MD5 not working with influxdb backups

### ISSUE THREAD

**Issue by wizzy99** [tiredofit/docker-db-backup#64]
### Summary

The influxdb backup sets $target to be a directory. md5sum doesn't work on directories, only on files.

generate_md5() {                                                                                              
if var_true "$MD5" ; then                                                                                                   
    print_notice "Generating MD5 for ${target}"                                
    cd $tmpdir                                                                                             
    **md5sum "${target}" > "${target}".md5**                                                                                    
    MD5VALUE=$(md5sum "${target}" | awk '{ print $1}')                                                                      
fi                                                                                                                          
} 

### Steps to reproduce

Back up any influxdb and enable md5

### What is the expected *correct* behavior?

md5 generated for each file in the backup set

### Relevant logs and/or screenshots

2021/05/14 11:28:50     /tmp/backups/influx_varken_192.168.111.11_20210514-105927/20210514T152841Z.s3140.tar.gz
2021/05/14 11:28:50     /tmp/backups/influx_varken_192.168.111.11_20210514-105927/20210514T152841Z.manifest
[NOTICE] ** [db-backup] Generating MD5 for influx_varken_192.168.111.11_20210514-105927
md5sum: can't read 'influx_varken_192.168.111.11_20210514-105927': Is a directory
md5sum: can't read 'influx_varken_192.168.111.11_20210514-105927': Is a directory

### Environment
Unraid running tiredofit/db-backup:latest
    
### Possible fixes
have a different md5 section in the run script for influxdb (and any other db's that have multi-file backup sets)

**Comment by tiredofit** [comment]
Resolved in the 3.xx series
