### ISSUE TITLE
MySQL backup may not work with non-root user

### ISSUE THREAD

**Issue by alwynpan** [tiredofit/docker-db-backup#72]
### Summary

MySQL backup may not work with non-root users in both manual and scheduled modes. Error message:

```
$ sudo docker exec -i backup backup-now
** Performing Manual Backup
[WARN] ** [db-backup] MySQL/MariaDB Server 'mysql' is not accessible, retrying.. (0 seconds so far)
[WARN] ** [db-backup] MySQL/MariaDB Server 'mysql' is not accessible, retrying.. (5 seconds so far)
[WARN] ** [db-backup] MySQL/MariaDB Server 'mysql' is not accessible, retrying.. (10 seconds so far)
[WARN] ** [db-backup] MySQL/MariaDB Server 'mysql' is not accessible, retrying.. (15 seconds so far)
...
```

### Steps to reproduce

Sample docker-compose file

```
version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
    container_name: MySQL

  backup:
    image: tiredofit/db-backup:2.6.1
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=test
      - DB_PASS=test
      - DB_NAME=test
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=43200
      - SPLIT_DB=FALSE
    container_name: backup
```

### What is the expected *correct* behavior?

Backup should work.

### Relevant logs and/or screenshots

```
$ sudo docker exec -i backup backup-now
** Performing Manual Backup
[WARN] ** [db-backup] MySQL/MariaDB Server 'mysql' is not accessible, retrying.. (0 seconds so far)
[WARN] ** [db-backup] MySQL/MariaDB Server 'mysql' is not accessible, retrying.. (5 seconds so far)
[WARN] ** [db-backup] MySQL/MariaDB Server 'mysql' is not accessible, retrying.. (10 seconds so far)
[WARN] ** [db-backup] MySQL/MariaDB Server 'mysql' is not accessible, retrying.. (15 seconds so far)
```

```
bash-5.1# mysql -u test -ptest -h mysql -e "SELECT COUNT(*) FROM information_schema.FILES;"
ERROR 1227 (42000) at line 1: Access denied; you need (at least one of) the PROCESS privilege(s) for this operation
```

### Environment

- Image version / tag:  2.6.1
- Host OS: Unbut
  
### Possible fixes

Use `mysqlshow` to test the database connection.

**Comment by alwynpan** [comment]
Created PR #73 for this issue. @tiredofit I am not entirely sure if it is a good solution, it looks a bit ugly to me. Please kindly check carefully. Thank you.

**Comment by tiredofit** [comment]
Interesting you are seeing this issue - Can we rule out this isn't a host issue? I am backing up over a hundred databases a day with this image. In the case of MySQL I personally use MariaDB but all databases are privileged to non root users.

**Comment by alwynpan** [comment]
@tiredofit I have tried on three different hosts and I saw the same issue. Also tested on a few old hosts, they worked fine. But when I updated the MySQL image to the latest 5.7, it stopped working.

**Comment by serotonie** [comment]
If this could help other, I had the same behaviour first time, I just deleted the quote mark arround the pw and it's now working...

**Comment by sbrunecker** [comment]
@tiredofit can you run `SHOW GRANTS;` for your non-root users? On mysql 8.0.27 I get

```
MySQL [test]> show grants;
+------------------------------------------------+
| Grants for test@%                              |
+------------------------------------------------+
| GRANT USAGE ON *.* TO `test`@`%`               |
| GRANT ALL PRIVILEGES ON `test`.* TO `test`@`%` |
+------------------------------------------------+
2 rows in set (0.001 sec)
```

**Comment by tiredofit** [comment]
````
+------------------------------------------------------------------------------------------------------------------+
| Grants for db@localhost                                                                                   |
+------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `db`@`localhost` IDENTIFIED BY PASSWORD '*AAAAAAAAAAAAAAAAAAAA' |
| GRANT ALL PRIVILEGES ON `db`.* TO `user`@`localhost`                                        |
+------------------------------------------------------------------------------------------------------------------+
2 rows in set (0.000 sec)

**Comment by sbrunecker** [comment]
I thought there would be additional privileges for information_schema but reading this [reply on stackexchange](https://dba.stackexchange.com/a/274460), I guess it makes sense. So in older versions users are simply allowed to access information_schema but need PROCESS privileges in newer ones.

**Comment by alwynpan** [comment]
> If this could help other, I had the same behaviour first time, I just deleted the quote mark arround the pw in my docker-compose.yml and it's now working...

Hmmm ... I don't have the quotes around the password ...

**Comment by tiredofit** [comment]
You can try `tiredofit/db-backup:2.10.3` to see if this issue is now resolved. The DB ready routines have been revamped to not require the `PROCESS` permission for the user now for Percona/MySQL users.
