### ISSUE TITLE
Sqlite file incorrectly detected as unreadable

### ISSUE THREAD

**Issue by tpansino** [tiredofit/docker-db-backup#78]
### Summary

Same issue as [this](https://github.com/alpinelinux/docker-alpine/issues/156#issuecomment-870839477) - `bash` in Alpine 3.14 returns an incorrect value (false) when using `[[ -r file ]]` on an otherwise readable file.

### Steps to reproduce

Set up a typical backup of a sqlite file, run `backup-now`, get an unreadable file error.

### What is the expected *correct* behavior?

No error, database is backed up.

### Environment

- Image version / tag: 2.8.1
- Host OS: Ubuntu 20.04

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

    
### Possible fixes

From the link above:
- Remove readability check
- Downgrade to Alpine 3.13
- Update to later version of Alpine (apparently one with kernel version 5.8+)

In the meantime I've found that rolling back to 2.6.1 of this tool fixes the issue, for anyone looking for a work-around.

**Comment by tpansino** [comment]
Also, maybe it's just my own experience, but I've found new Alpine images regularly have bugs like this in them. I know folks really like the smaller size images, but I've stopped using Alpine entirely in favor of Ubuntu or Debian slim images, which seem to have fewer regressions.

I'd love to see an image of this project based on either of these, but I recognize that's a lot to ask for.

**Comment by tiredofit** [comment]
What is your host OS and Kernel ver? Pre 5.8 gets weird if I recall.

**Comment by tpansino** [comment]
I'm on Ubuntu 20.04 with `5.11.0-36-generic` for the kernel.

I'm also on `runc = 1.0.0~rc95-0ubuntu1~20.04.2`, and the problem still exists after a full reboot even though that thread says it was fixed as of `1.0.0-r93`. 🤷

**Comment by tiredofit** [comment]
Sometimes the version numbers don't match up. I am foggy as to when my own issue came up (I run Arch though) and if it was 5.10 that almost seems like a year ago, time flies. I do recall Alpine 3.13 and edge breaking spectacularly so the timing could be right.

I do have some work to do on the db-backup image and will see what I can do about doing a deb build.  My base images are built in both alpine and debian so theoretically if the same packages were installed the same routines and functions should work without any change. I'm super swamped with getting my school open this year, so likely won't have many cycles until mid October.

**Comment by tpansino** [comment]
Good news - this issue seems to be resolved in the latest version of the container. I'm guessing Alpine's patch for this finally made it into wherever it needed to be 🤷
