### ISSUE TITLE
Docker image tagged latest is different from latest version image

### ISSUE THREAD

**Issue by sbrunecker** [tiredofit/docker-db-backup#85]
### Summary

The image tagged as `latest` is not the same as the image tagged with the most recent version.

### Steps to reproduce

The latest version is currently 2.9.1 and should include the fix from #83. If `latest` and `2.9.1` were the same image, the following commands should give the same results but do not:

Plugin directory of `latest` is empty:

```shell
$ docker pull tiredofit/db-backup:latest
$ docker run --rm --entrypoint bash tiredofit/db-backup:latest -c 'ls /usr/lib/mariadb/plugin/'
```

Plugin directory of `2.9.1` contains plugins as expected:

```
$ docker pull tiredofit/db-backup:2.9.1
$ docker run --rm --entrypoint bash tiredofit/db-backup:2.9.1 -c 'ls /usr/lib/mariadb/plugin/'
caching_sha2_password.so
client_ed25519.so
dialog.so
mysql_clear_password.so
sha256_password.so
```

### What is the expected *correct* behavior?

I was expecting `latest` tag to point to the same image as 2.9.1.

**Comment by sbrunecker** [comment]
It contains the changes from #84 so it seems the images weren't pushed in the order of the commits. Maybe there's a way to cancel old build jobs when a new one is started?

**Comment by tiredofit** [comment]
Github actions was throwing some weird errors yesterday with tags - I'm retrying one, if not I will build one locally and push manually.
