### ISSUE TITLE
S3_HOST documented but not being used anymore / add support with endpoint-url

### ISSUE THREAD

**Issue by ToshY** [tiredofit/docker-db-backup#89]
### Summary
I'm actually in need of storing backups to a bucket in [Backblaze](https://help.backblaze.com/hc/en-us/articles/360047779633-Configuring-the-AWS-CLI-for-use-with-B2). Before diving into the code and just going with the README, it seemed that `S3_HOST` would be the way to go. But I saw that it's usage was removed since [this commit](https://github.com/tiredofit/docker-db-backup/commit/353b1af7b49ad21d71d94cd4989e18730ebdbc38).

**Edit**
Similar related issue #87

### What is the expected *correct* behavior?
Being able to store backups to Backblaze bucket.

### Possible fixes
Adding an extra environment variable, e.g. `S3_ENDPOINT`, which could then be used with the `--endpoint-url` argument.
```
aws s3 cp ${tmpdir}/${target}/ s3://${S3_BUCKET}/${target} --endpoint-url=${S3_ENDPOINT}
```
See [Backblaze - "How to use s3cmd with Backblaze B2 Cloud Storage"](https://help.backblaze.com/hc/en-us/articles/360047779633-Configuring-the-AWS-CLI-for-use-with-B2) for more information.

**Sidenote**
It also seems that currently if I would like to save the backups to the root of the bucket, that the command
```
aws s3 cp ${tmpdir}/${target} s3://${S3_BUCKET}/${S3_PATH}/${target}
```

will result in 

```
aws s3 cp ${tmpdir}/${target} s3://${S3_BUCKET}//${target}
```

if `S3_PATH` is set to empty, which doesn't seem correct. So it would be nice if this could be improved, and possibly set the `S3_PATH` default to root of bucket.

**Comment by cdstg** [comment]
Yes same problem here with non AWS how to set the s3_host ?

**Comment by ToshY** [comment]
@cdstg it currently doesn't seem possible here. I already switched to using [databacker/mysql-backup](https://github.com/databacker/mysql-backup) which supports other endpoints as well. The only thing it doesn't include out of the box is log rotation, but can be easily be added by creating a new image like stated [here](https://github.com/databacker/mysql-backup/issues/9#issuecomment-345730076).

**Comment by phamleduy04** [comment]
Same problem here with non AWS. Any recommendation for redis backup?

**Comment by jacksgt** [comment]
Hello friends,

it appears that since release 2.11.0 (in particular https://github.com/tiredofit/docker-db-backup/commit/4d6419fd184590c3620a7a9a5e70ef3adecb97ee ) this variable is actually functional again!
I got it working with this config:
```sh
BACKUP_LOCATION=S3
BACKUP_TYPE=S3 # note: both variables currently need to be set!
S3_BUCKET=my-bucket
S3_HOST=s3.us-west-001.backblazeb2.com
S3_KEY_ID=foo
S3_KEY_SECRET=bar
S3_PATH=backup
S3_REGION=us-west-001
S3_URI_STYLE=Path # note: this needs to be set, but doesn't do anything
```
which generates the correct command:
```
aws --endpoint-url https://s3.us-west-001.backblazeb2.com s3 cp /tmp/backups/mysql_test_mariadb_20220205-231128.sql.bz2 s3://my-bucket/backup/mysql_test_mariadb_20220205-231128.sql.bz2
```

Good luck!
