### ISSUE TITLE
Vers 2.10.3 fails availability test for root user in Mariadb/mysql

### ISSUE THREAD

**Issue by rcutcliffe** [tiredofit/docker-db-backup#94]
### Summary

====== This is my first issue post, so excuse me if I did something wrong =================

Manual backups fail database availability test when run as root user in MariaDB (I assume also in Mysql)

### Steps to reproduce

Deploy version 2.10.3 container, run backup-now.

### What is the expected *correct* behavior?

Backup should proceed using the given parameters.  Version 2.10.2 works okay.

### Environment
Running in Docker on OpenMediaVault 6 on a Raspberry Pi

- Image version / tag:  
- Host OS:  Raspbery Pi OS Lite version

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

    
### Possible fixes

===============================  Cut from etc/services.available/10-db-backup/run ================
        "mysql" )
            COUNTER=0
            export MYSQL_PWD=${dbpass}
            while ! (mysql -u"${dbuser}" -P"${dbport}" -h"${dbhost}" -e "SHOW GRANTS FOR CURRENT_USER;" 2>&1 | grep -E "GRANT ALL PRIVILEGES ON \`${DB_NAME}\`" > /dev/null 2>&1) ; do
              sleep 5
              (( COUNTER+=5 ))
              print_warn "MySQL/MariaDB Server '${maria_host}' is not accessible, retrying.. ($counter seconds so far)"
            done
        ;;

============================END  Cut from etc/services.available/10-db-backup/run ================

Grants for root user are returned as 'GRANT ALL PRIVILEGES ON *.* to root..........................   This will fail the grep for $DB_NAME, unless you specify '*.*' as your DB_NAME.

Additionally, the variable ${maria_host} is unknown causing missing information in the error message, and the $counter variable in the error message should be in UPPER case.

**Comment by the1ts** [comment]
@rcutcliffe is correct, those using a single user for backup of all DBs may get ```*.*``` or some wildcard for the DB so the test against each DB will fail even though the required rights are granted.
Also, not sure the test of ```-e "SHOW GRANTS FOR CURRENT_USER;" | grep -E "GRANT ALL PRIVILEGES ON"``` is valid for everyone. Many people will use software that doesn't insert ```GRANT ALL```, but lists the rights specifically and will therefore fail this test. 
Further, people may use a non-root user with only the required rights (subset of ALL), enough to do the job including backup, but will fail this test.
One of my show grants on a valid user used for docker-db-backup now, lists 30 rights but fails this test ignoring the DB wildcard issue.

**Comment by elad-bar** [comment]
happens here also

**Comment by Ixian** [comment]
Confirming same problem(s) with 2.10.3 - backup of all dbs is broken due to problem outlined above, I also noticed the typo in `print_warn "MySQL/MariaDB Server '${maria_host}' is not accessible, retrying.. ($counter seconds so far)"` which causes an empty string to return in the error message, this one may just be cosmetic.

I reverted to the 2.10.2 image with the old check and it works fine.

**Comment by tiredofit** [comment]
Version 2.11.0 should resolve all of the above issues.

**Comment by rcutcliffe** [comment]
Thanks Dave.

**Comment by jacksgt** [comment]
Hey, I can confirm that this works as expected in version 2.11.0 with MariaDB. I think this issue can be closed.
